version: "3"

services:

  etracs-server:
    container_name: etracs-server
    image: ramesesinc/etracs-server-city:2.5.02.07.01
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
    volumes:
      - ./modules:/apps/etracs25/modules

      - ../../_custom/datasources:/services/datasources
      - ../../_res/connections:/apps/etracs25/connections/ext
      - ../../_custom/module-server:/apps/etracs25/modules/ext/zzz-lgu-custom-module

      - ./module-client/reports:/apps/server/templates
      - ../../_custom/module-client/etracs:/apps/server/templates/custom
      - ../../_custom/output:/apps/server/output

      - ./dev-modules/rameses-gov-etracs-tools.jar:/services/modules/etracs/rameses-gov-etracs-tools.jar
      - ./dev-modules/rameses-gov-etracs-bpls-online-services.jar:/services/modules/bpls/rameses-gov-etracs-bpls-online-services.jar
      - ./dev-modules/rameses-gov-etracs-rptis-online-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-online-services.jar
      - ./dev-modules/rameses-gov-etracs-rptis-services.jar:/services/modules/rptis/rameses-gov-etracs-rptis-services.jar
