-- MIGRATION
USE obo_puerto_template;

if object_id('dbo.ztmp_sys_role', 'U') IS NOT NULL 
   drop table dbo.ztmp_sys_role; 
go
CREATE TABLE [dbo].[ztmp_sys_role] (
[name] varchar(50) NOT NULL ,
[title] varchar(255) NULL ,
[system] int NULL 
)
GO
INSERT INTO ztmp_sys_role VALUES ('ADMIN', 'ADMIN', 1);
INSERT INTO ztmp_sys_role VALUES ('APPROVER', 'APPROVER', 1);
INSERT INTO ztmp_sys_role VALUES ('ARCHITECTURAL_APPROVER', 'ARCHITECTURAL APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('ARCHITECTURAL_EVALUATOR', 'ARCHITECTURAL EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('ARCHITECTURAL_INSPECTOR', 'ARCHITECTURAL INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('ARCHITECTURAL_REVIEWER', 'ARCHITECTURAL REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('ASSESSOR', 'ASSESSOR', 1);
INSERT INTO ztmp_sys_role VALUES ('BFP_APPROVER', 'BFP APPROVER', 1);
INSERT INTO ztmp_sys_role VALUES ('BFP_EVALUATOR', 'BFP EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('BFP_INSPECTOR', 'BFP INSPECTOR', 1);
INSERT INTO ztmp_sys_role VALUES ('BFP_RELEASER', 'BFP RELEASER', 1);
INSERT INTO ztmp_sys_role VALUES ('BFP_REVIEWER', 'BFP REVIEWER', 1);
INSERT INTO ztmp_sys_role VALUES ('CIVIL_STRUCTURAL_APPROVER', 'CIVIL STRUCTURAL APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('CIVIL_STRUCTURAL_EVALUATOR', 'CIVIL_STRUCTURAL_EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('CIVIL_STRUCTURAL_INSPECTOR', 'CIVIL STRUCTURAL INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('CIVIL_STRUCTURAL_REVIEWER', 'CIVIL STRUCTURAL REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('COORDINATOR', 'OBO COORDINATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('EDITOR', 'EDITOR', 0);
INSERT INTO ztmp_sys_role VALUES ('ELECTRICAL_APPROVER', 'ELECTRICAL APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('ELECTRICAL_EVALUATOR', 'ELECTRICAL EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('ELECTRICAL_INSPECTOR', 'ELECTRICAL INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('ELECTRICAL_REVIEWER', 'ELECTRICAL REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('ELECTRONIC_APPROVER', 'ELECTRONIC APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('ELECTRONIC_EVALUATOR', 'ELECTRONIC_EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('ELECTRONIC_INSPECTOR', 'ELECTRONIC INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('ELECTRONIC_REVIEWER', 'ELECTRONIC REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('LINE_AND_GRADE_APPROVER', 'LINE AND GRADE APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('LINE_AND_GRADE_EVALUATOR', 'LINE_AND_GRADE_EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('LINE_AND_GRADE_INSPECTOR', 'LINE AND GRADE INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('LINE_AND_GRADE_REVIEWER', 'LINE AND GRADE REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('MASTER', 'MASTER', 1);
INSERT INTO ztmp_sys_role VALUES ('MECHANICAL_APPROVER', 'MECHANICAL APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('MECHANICAL_EVALUATOR', 'MECHANICAL EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('MECHANICAL_INSPECTOR', 'MECHANICAL INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('MECHANICAL_REVIEWER', 'MECHANICAL REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('PLUMBING_APPROVER', 'PLUMBING APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('PLUMBING_EVALUATOR', 'PLUMBING EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('PLUMBING_INSPECTOR', 'PLUMBING INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('PLUMBING_REVIEWER', 'PLUMBING REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('RECEIVER', 'RECEIVER', 1);
INSERT INTO ztmp_sys_role VALUES ('RELEASER', 'OBO RELEASER', 1);
INSERT INTO ztmp_sys_role VALUES ('REQUIREMENT_REVIEWER', 'OBO REQUIREMENT_REVIEWER', 1);
INSERT INTO ztmp_sys_role VALUES ('REVIEWER', 'OBO REVIEWER', 1);
INSERT INTO ztmp_sys_role VALUES ('RPT_APPROVER', 'OBO RPT_APPROVER', 1);
INSERT INTO ztmp_sys_role VALUES ('RPT_INSPECTOR', 'OBO RPT_INSPECTOR', 1);
INSERT INTO ztmp_sys_role VALUES ('RPT_REVIEWER', 'OBO RPT_REVIEWER', 1);
INSERT INTO ztmp_sys_role VALUES ('RULE_AUTHOR', 'OBO RULE_AUTHOR', 1);
INSERT INTO ztmp_sys_role VALUES ('SANITARY_APPROVER', 'SANITARY APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('SANITARY_EVALUATOR', 'SANITARY EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('SANITARY_INSPECTOR', 'SANITARY INSPECTOR', 0);
INSERT INTO ztmp_sys_role VALUES ('SANITARY_REVIEWER', 'SANITARY REVIEWER', 0);
INSERT INTO ztmp_sys_role VALUES ('SHARED', 'OBO SHARED', 1);
INSERT INTO ztmp_sys_role VALUES ('SITE_APPROVER', 'SITE APPROVER', 0);
INSERT INTO ztmp_sys_role VALUES ('SITE_EVALUATOR', 'OBO SITE_EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('SITE_INSPECTOR', 'SITE INSPECTOR', 1);
INSERT INTO ztmp_sys_role VALUES ('SITE_REVIEWER', 'OBO SITE_REVIEWER', 1);
INSERT INTO ztmp_sys_role VALUES ('SUPERVISOR', 'SUPERVISOR', 0);
INSERT INTO ztmp_sys_role VALUES ('SYSTEM', 'OBO SYSTEM', 1);
INSERT INTO ztmp_sys_role VALUES ('WF_EDITOR', 'WORKFLOW EDITOR', 0);
INSERT INTO ztmp_sys_role VALUES ('ZONING_APPROVER', 'ZONING APPROVER', 1);
INSERT INTO ztmp_sys_role VALUES ('ZONING_COORDINATOR', 'ZONING COORDINATOR', 0);
INSERT INTO ztmp_sys_role VALUES ('ZONING_EVALUATOR', 'ZONING EVALUATOR', 1);
INSERT INTO ztmp_sys_role VALUES ('ZONING_RELEASER', 'OBO ZONING_RELEASER', 1);
INSERT INTO ztmp_sys_role VALUES ('ZONING_REVIEWER', 'ZONING REVIEWER', 1);

insert into sys_role 
select * 
from ztmp_sys_role z 
where z.name not in (
	select name from sys_role where name = z.name 
)
go 
drop table ztmp_sys_role
go 



insert into sys_signature ( 
	objid, userid, user_name, displayname, position, signature, tag, system, state 
) 
SELECT 
	objid, userid, user_name, displayname, position, signature, tag, system, state 
FROM obo_puerto.dbo.sys_signature s 
where objid not in (
	select objid from sys_signature where objid = s.objid 
)
go 
update aa set 
	aa.signature = bb.signature 
from sys_signature aa, obo_puerto.dbo.sys_signature bb 
where aa.objid = bb.objid 
go 


INSERT INTO sys_sequence 
SELECT * FROM obo_puerto.dbo.sys_sequence s 
where s.objid not in (
	select objid from sys_sequence where objid = s.objid 
)
go 
INSERT INTO sys_user 
SELECT * FROM obo_puerto.dbo.sys_user u 
where u.objid not in (
	select objid from sys_user where objid = u.objid 
)
go 
INSERT INTO sys_user_role 
SELECT * FROM obo_puerto.dbo.sys_user_role r 
where r.objid not in (
	select objid from sys_user_role where objid = r.objid 
)
go 





if object_id('dbo.ztmp_obo_taskitem_type', 'U') IS NOT NULL 
   drop table dbo.ztmp_obo_taskitem_type; 
go
CREATE TABLE ztmp_obo_taskitem_type (
[objid] varchar(50) NOT NULL ,
[apptype] varchar(50) NULL ,
[title] varchar(100) NULL ,
[sectionid] varchar(50) NULL ,
[sortindex] int NULL ,
[required] int NULL ,
[activationstate] varchar(50) NULL ,
[joinstate] varchar(50) NULL 
)
go 

INSERT INTO ztmp_obo_taskitem_type VALUES 
('OCCUPANCY:ARCHITECTURAL','occupancy_certificate','Architectural','ARCHITECTURAL',3,1,'inspection','inspection'),
('OCCUPANCY:CIVIL_STRUCTURAL','occupancy_certificate','Civil/Structural','CIVIL_STRUCTURAL',4,1,'inspection','inspection'),
('OCCUPANCY:ELECTRICAL','occupancy_certificate','Electrical','ELECTRICAL',5,1,'inspection','inspection'),
('OCCUPANCY:ELECTRONIC','occupancy_certificate','Electronic','ELECTRONIC',9,0,'inspection','inspection'),
('OCCUPANCY:FSIC','occupancy_certificate','Fire Safety Inspection','BFP',1,1,'inspection','inspection'),
('OCCUPANCY:LINE_AND_GRADE','occupancy_certificate','Line and Grade',NULL,2,1,'inspection','inspection'),
('OCCUPANCY:MECHANICAL','occupancy_certificate','Mechanical','MECHANICAL',6,0,'inspection','inspection'),
('OCCUPANCY:PLUMBING','occupancy_certificate','Plumbing','PLUMBING',8,0,'inspection','inspection'),
('OCCUPANCY:SANITARY','occupancy_certificate','Sanitary','SANITARY',9,0,'inspection','inspection');

insert into obo_taskitem_type 
select * from ztmp_obo_taskitem_type z 
where objid not in (
	select objid from obo_taskitem_type where objid = z.objid 
)
go 

drop table ztmp_obo_taskitem_type
go 



if object_id('dbo.ztmp_obo_taskitem_type_role', 'U') IS NOT NULL 
   drop table dbo.ztmp_obo_taskitem_type_role; 
go
CREATE TABLE [dbo].[ztmp_obo_taskitem_type_role] (
[objid] varchar(50) NOT NULL ,
[typeid] varchar(50) NULL ,
[state] varchar(50) NULL ,
[role] varchar(50) NULL  
)
GO

INSERT INTO ztmp_obo_taskitem_type_role VALUES 
('BETR4cc44b45:17968cdabef:-7fe7','OCCUPANCY:SANITARY','approval','SANITARY_APPROVER'),
('BETR4cc44b45:17968cdabef:-7fe8','OCCUPANCY:SANITARY','review','SANITARY_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7fe9','OCCUPANCY:SANITARY','evaluation','SANITARY_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7fea','OCCUPANCY:ELECTRONIC','approval','ELECTRONIC_APPROVER'),
('BETR4cc44b45:17968cdabef:-7feb','OCCUPANCY:ELECTRONIC','review','ELECTRONIC_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7fec','OCCUPANCY:ELECTRONIC','evaluation','ELECTRONIC_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7fed','OCCUPANCY:PLUMBING','approval','PLUMBING_APPROVER'),
('BETR4cc44b45:17968cdabef:-7fee','OCCUPANCY:PLUMBING','review','PLUMBING_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7fef','OCCUPANCY:PLUMBING','evaluation','PLUMBING_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff0','OCCUPANCY:MECHANICAL','approval','MECHANICAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ff1','OCCUPANCY:MECHANICAL','review','MECHANICAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ff2','OCCUPANCY:MECHANICAL','evaluation','MECHANICAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff3','OCCUPANCY:ELECTRICAL','approval','ELECTRICAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ff4','OCCUPANCY:ELECTRICAL','review','ELECTRICAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ff5','OCCUPANCY:ELECTRICAL','evaluation','ELECTRICAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff6','OCCUPANCY:CIVIL_STRUCTURAL','approval','CIVIL_STRUCTURAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ff7','OCCUPANCY:CIVIL_STRUCTURAL','review','CIVIL_STRUCTURAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ff8','OCCUPANCY:CIVIL_STRUCTURAL','evaluation','CIVIL_STRUCTURAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff9','OCCUPANCY:ARCHITECTURAL','approval','ARCHITECTURAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ffa','OCCUPANCY:ARCHITECTURAL','review','ARCHITECTURAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ffb','OCCUPANCY:ARCHITECTURAL','evaluation','ARCHITECTURAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ffe','OCCUPANCY:LINE_AND_GRADE','approval','LINE_AND_GRADE_APPROVER'),
('BETR4cc44b45:17968cdabef:-7fff','OCCUPANCY:LINE_AND_GRADE','review','LINE_AND_GRADE_REVIEWER'),
('BETR4cc44b45:17968cdabef:-8000','OCCUPANCY:LINE_AND_GRADE','evaluation','LINE_AND_GRADE_INSPECTOR'),
('FSIC_BFP_APPROVER','OCCUPANCY:FSIC','approval','BFP_APPROVER'),
('FSIC_BFP_INSPECTOR','OCCUPANCY:FSIC','evaluation','BFP_INSPECTOR'),
('FSIC_BFP_REVIEWER','OCCUPANCY:FSIC','review','BFP_REVIEWER')
go 

INSERT INTO ztmp_obo_taskitem_type_role VALUES 
('BETR4cc44b45:17968cdabef:-7fe7','OCCUPANCY:SANITARY','approval','SANITARY_APPROVER'),
('BETR4cc44b45:17968cdabef:-7fe8','OCCUPANCY:SANITARY','review','SANITARY_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7fe9','OCCUPANCY:SANITARY','evaluation','SANITARY_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7fea','OCCUPANCY:ELECTRONIC','approval','ELECTRONIC_APPROVER'),
('BETR4cc44b45:17968cdabef:-7feb','OCCUPANCY:ELECTRONIC','review','ELECTRONIC_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7fec','OCCUPANCY:ELECTRONIC','evaluation','ELECTRONIC_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7fed','OCCUPANCY:PLUMBING','approval','PLUMBING_APPROVER'),
('BETR4cc44b45:17968cdabef:-7fee','OCCUPANCY:PLUMBING','review','PLUMBING_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7fef','OCCUPANCY:PLUMBING','evaluation','PLUMBING_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff0','OCCUPANCY:MECHANICAL','approval','MECHANICAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ff1','OCCUPANCY:MECHANICAL','review','MECHANICAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ff2','OCCUPANCY:MECHANICAL','evaluation','MECHANICAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff3','OCCUPANCY:ELECTRICAL','approval','ELECTRICAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ff4','OCCUPANCY:ELECTRICAL','review','ELECTRICAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ff5','OCCUPANCY:ELECTRICAL','evaluation','ELECTRICAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff6','OCCUPANCY:CIVIL_STRUCTURAL','approval','CIVIL_STRUCTURAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ff7','OCCUPANCY:CIVIL_STRUCTURAL','review','CIVIL_STRUCTURAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ff8','OCCUPANCY:CIVIL_STRUCTURAL','evaluation','CIVIL_STRUCTURAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ff9','OCCUPANCY:ARCHITECTURAL','approval','ARCHITECTURAL_APPROVER'),
('BETR4cc44b45:17968cdabef:-7ffa','OCCUPANCY:ARCHITECTURAL','review','ARCHITECTURAL_REVIEWER'),
('BETR4cc44b45:17968cdabef:-7ffb','OCCUPANCY:ARCHITECTURAL','evaluation','ARCHITECTURAL_INSPECTOR'),
('BETR4cc44b45:17968cdabef:-7ffe','OCCUPANCY:LINE_AND_GRADE','approval','LINE_AND_GRADE_APPROVER'),
('BETR4cc44b45:17968cdabef:-7fff','OCCUPANCY:LINE_AND_GRADE','review','LINE_AND_GRADE_REVIEWER'),
('BETR4cc44b45:17968cdabef:-8000','OCCUPANCY:LINE_AND_GRADE','evaluation','LINE_AND_GRADE_INSPECTOR'),
('FSIC_BFP_APPROVER','OCCUPANCY:FSIC','approval','BFP_APPROVER'),
('FSIC_BFP_INSPECTOR','OCCUPANCY:FSIC','evaluation','BFP_INSPECTOR'),
('FSIC_BFP_REVIEWER','OCCUPANCY:FSIC','review','BFP_REVIEWER');


insert into obo_taskitem_type_role 
select distinct z.* 
from ztmp_obo_taskitem_type_role z, sys_role r 
where r.name = z.role 
	and z.objid not in (
		select objid from obo_taskitem_type_role where objid = z.objid
	)
go 

drop table ztmp_obo_taskitem_type_role
go 



if object_id('dbo.ztmp_obo_doctype', 'U') IS NOT NULL 
   drop table dbo.ztmp_obo_doctype; 
go
CREATE TABLE [dbo].[ztmp_obo_doctype] (
[objid] varchar(50) NOT NULL ,
[title] varchar(100) NULL ,
[sectionid] varchar(50) NULL ,
[sortorder] smallint NULL ,
[type] varchar(50) NULL ,
[template] varchar(50) NULL ,
[autocreate] int NULL ,
[issuetype] int NULL ,
[requirefee] int NULL ,
[appnopattern] varchar(50) NULL ,
[controlnopattern] varchar(50) NULL ,
[subtypeof] varchar(50) NULL ,
[apptype] varchar(50) NULL ,
[system] int NULL ,
[role] varchar(50) NULL ,
[endorserid] varchar(50) NULL ,
[approverid] varchar(50) NULL ,
[reportheader] varchar(50) NULL ,
[refdoc] varchar(50) NULL ,
[includeinemail] int NULL
)
GO

INSERT INTO ztmp_obo_doctype VALUES 
('ACCESSORIES','ACCESSORIES','CIVIL_STRUCTURAL',0,'REGULAR',NULL,0,0,1,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('ARCHITECTURAL','ARCHITECTURAL PERMIT','ARCHITECTURAL',2,'REGULAR',NULL,0,1,0,NULL,'[parentno]-A',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('BFP_SALES_TAX','BFP SALES TAX (OCCUPANCY)','BFP',20,'REGULAR',NULL,0,0,1,NULL,NULL,NULL,'occupancy_certificate',0,NULL,NULL,NULL,NULL,NULL,NULL),
('BUILDING_PERMIT','BUILDING PERMIT',NULL,0,'MAIN','reports/obo/building_permit',1,1,1,'BPAPP-[yyyyMM]-[%05d]','BP-[YYYYMM]-[%05d]',NULL,'building_permit',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,1),
('BUILDING_RPT','BUILDING RPT','RPT',12,'REGULAR',NULL,1,0,1,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('CIVIL_STRUCTURAL','CIVIL/STRUCTURAL PERMIT','CIVIL_STRUCTURAL',3,'REGULAR',NULL,NULL,1,0,NULL,'[parentno]-C',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('DEMOLITION','DEMOLITION PERMIT',NULL,20,'REGULAR',NULL,NULL,1,NULL,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('ELECTRICAL','ELECTRICAL PERMIT','ELECTRICAL',4,'REGULAR',NULL,NULL,1,1,NULL,'[parentno]-E',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('ELECTRONIC','ELECTRONICS PERMIT','ELECTRONIC',8,'REGULAR',NULL,NULL,1,1,NULL,'[parentno]-EC',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('EXCAVATION','EXCAVATION AND GROUND PERMIT',NULL,21,'REGULAR',NULL,NULL,0,1,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('FENCING','FENCING PERMIT',NULL,9,'REGULAR',NULL,NULL,0,1,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('FINAL_ELECTRICAL_INSPECTION','CERTIFICATE OF FINAL ELECTRICAL INSPECTION','ELECTRICAL',0,'MAIN','reports/obo/final_electrical_inspection',1,1,1,NULL,'CFEI-[yyyyMMdd]-[%05d]',NULL,'occupancy_certificate',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,1),
('FSEC','FIRE SAFETY EVALUATION CLEARANCE','BFP',12,'MAIN','reports/bfp/fsec',1,2,1,NULL,NULL,NULL,'building_permit',0,'BFP_RELEASER','-19b3742e:1772823a0be:-7fd4','-19b3742e:1772823a0be:-7fd3',NULL,NULL,1),
('FSEC_CHECKLIST','FIRE SAFETY EVALUATION CHECKLIST','BFP',13,'REGULAR','reports/bfp/fsec_checklist',1,2,NULL,NULL,NULL,'FSEC','building_permit',0,'ZONING_RELEASER','-19b3742e:1772823a0be:-7fd4','-19b3742e:1772823a0be:-7fd3',NULL,'FSEC',1),
('FSIC','FIRE SAFETY INSPECTION CERTIFICATE','BFP',1,'MAIN','reports/bfp/fsic',1,2,2,NULL,NULL,NULL,'occupancy_certificate',0,'BFP_RELEASER','-19b3742e:1772823a0be:-7fd4','-19b3742e:1772823a0be:-7fd3',NULL,NULL,1),
('HOT_WORKS','HOT WORKS PERMIT','BFP',15,'REGULAR','reports/bfp/hotworks_clearance',NULL,2,1,NULL,NULL,NULL,'building_permit',0,'BFP_RELEASER','-19b3742e:1772823a0be:-7fd4','-19b3742e:1772823a0be:-7fd3',NULL,'FSEC',1),
('LINE_AND_GRADE','LINE AND GRADE','LINE_AND_GRADE',1,'REGULAR',NULL,1,1,1,NULL,'[parentno]-LG',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('LOCATIONAL_CLEARANCE','LOCATIONAL CLEARANCE','ZONING',100,'MAIN','reports/zoning/locational_clearance',1,2,1,NULL,'LOC-[yyyyMM]-[%05d]',NULL,'building_permit',0,'ZONING_RELEASER','783eacf6:1772ef3e481:-8000','783eacf6:1772ef3e481:-7fff',NULL,NULL,1),
('MECHANICAL','MECHANICAL PERMIT','MECHANICAL',5,'REGULAR',NULL,NULL,1,1,NULL,'[parentno]-M',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('NOTICE_OF_VIOLATION','NOTICE OF VIOLATION','ARCHITECTURAL',10,'REGULAR',NULL,0,0,1,NULL,NULL,NULL,'occupancy_certificate',0,NULL,NULL,NULL,NULL,NULL,NULL),
('OCCUPANCY_CERTIFICATE','OCCUPANCY CERTIFICATE',NULL,0,'MAIN','reports/obo/occupancy_certificate',1,1,1,'OCCAPP-[yyyyMM]-[%05d]','OP-[YYYYMM]-[%05d]',NULL,'occupancy_certificate',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,1),
('OCCUPANCY_CERTIFICATE_REQUIREMENT_TRANSMITTAL','OCCUPANCY CERTIFICATE REQUIREMENT TRANSMITTAL',NULL,1,'REPORT','reports/obo/requirement_transmittal',NULL,NULL,NULL,NULL,'OP-RT-[yyyyMM]-[%05d]',NULL,'occupancy_certificate',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,NULL),
('OCCUPANCY_INSPECTION_TRANSMITTAL','OCCUPANCY INSPECTION FINDING TRANSMITTAL',NULL,2,'REPORT','reports/obo/finding_transmittal',NULL,NULL,NULL,NULL,'OPF-[yyyyMM]-[%05d]',NULL,'occupancy_certificate',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,NULL),
('PLUMBING','PLUMBING PERMIT','PLUMBING',7,'REGULAR',NULL,NULL,1,1,NULL,'[parentno]-P',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('REQUIREMENT_TRANSMITTAL','REQUIREMENT TRANSMITTAL',NULL,NULL,'REPORT','reports/obo/requirement_transmittal',NULL,NULL,NULL,NULL,'BP-RT-[yyyyMM]-[%05d]',NULL,'building_permit',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,NULL),
('SANITARY','SANITARY PERMIT','SANITARY',6,'REGULAR',NULL,NULL,1,NULL,NULL,'[parentno]-S',NULL,'building_permit',0,NULL,NULL,NULL,NULL,'BUILDING_PERMIT',NULL),
('SCAFFOLDING','SCAFFOLDING PERMIT',NULL,12,'REGULAR',NULL,NULL,0,1,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('SIDEWALK_CONSTRUCTION','SIDEWALK CONSTRUCTION PERMIT',NULL,10,'REGULAR',NULL,NULL,0,NULL,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('SIGN','SIGN PERMIT',NULL,13,'REGULAR',NULL,NULL,0,1,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('TEMPORARY_SERVICE_CONNECTION','PERMIT FOR TEMPORARY SERVICE CONNECTION',NULL,14,'REGULAR',NULL,NULL,1,NULL,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('TEMPORARY_SIDEWALK_ENCLOSURE_AND_OCCUPANCY','TEMPORARY SIDEWALK ENCLOSURE AND OCCUPANCY PERMIT',NULL,11,'REGULAR',NULL,NULL,0,NULL,NULL,NULL,NULL,'building_permit',0,NULL,NULL,NULL,NULL,NULL,NULL),
('TRADE_EVALUATION_TRANSMITTAL','BUILDING PERMIT EVALUATION',NULL,0,'REPORT','reports/obo/finding_transmittal',NULL,NULL,NULL,NULL,'BTET-[yyyyMM]-[%05d]',NULL,'building_permit',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,NULL),
('ZONING_EVALUATION_TRANSMITTAL','BUILDING PERMIT ZONING EVALUATION',NULL,NULL,'REPORT','reports/obo/finding_transmittal',NULL,NULL,NULL,NULL,'ZFT-[yyyyMM]-[%05d]',NULL,'building_permit',0,NULL,'-19b3742e:1772823a0be:-7fd1','-19b3742e:1772823a0be:-7fd0',NULL,NULL,NULL);

insert into obo_doctype 
select 
	z.objid, z.title, z.sectionid, z.sortorder, z.type, z.template, z.autocreate, z.issuetype, 
	z.requirefee, z.appnopattern, z.controlnopattern, z.subtypeof, z.apptype, z.system, z.role, 
	se.objid as endorserid, sa.objid as approverid, z.reportheader, z.refdoc, z.includeinemail  
from ztmp_obo_doctype z 
	left join sys_signature sa on sa.objid = z.approverid 
	left join sys_signature se on se.objid = z.endorserid 
where 
	z.objid not in (
		select objid from obo_doctype where objid = z.objid 
	)
go 

drop table ztmp_obo_doctype
go 



if object_id('dbo.ztmp_obo_variable', 'U') IS NOT NULL 
   drop table dbo.ztmp_obo_variable; 
go
CREATE TABLE [dbo].[ztmp_obo_variable] (
[objid] varchar(50) NOT NULL ,
[state] varchar(50) NULL ,
[name] varchar(50) NULL ,
[caption] varchar(255) NULL ,
[description] varchar(255) NULL ,
[datatype] varchar(100) NULL ,
[doctypeid] varchar(50) NULL ,
[category] varchar(255) NULL ,
[sortorder] smallint NULL ,
[system] smallint NULL ,
[arrayvalues] text NULL ,
[unit] varchar(100) NULL ,
[occupancytypeid] varchar(50) NULL ,
[lookuplistname] varchar(50) NULL ,
[multiselect] int NULL 
)
GO

INSERT INTO ztmp_obo_variable VALUES 
('ACCESS_TO_PUBLIC_STREET','DRAFT','ACCESS_TO_PUBLIC_STREET','ACCESS TO PUBLIC STREET',NULL,'decimal','ARCHITECTURAL','C',22,0,NULL,'UNIT',NULL,NULL,NULL),
('ANTENNA_TOWER_COMMUNICATION','DRAFT','ANTENNA_TOWER_COMMUNICATION','ANTENNA TOWERS/MASTS OR OTHER STRUCTURES FOR COMMUNICATIONS TRANSMISSION',NULL,'integer','ELECTRONIC','G',29,0,NULL,'STRUCTURE',NULL,NULL,NULL),
('ATM_TICKETING','DRAFT','ATM_TICKETING','AUTOMATED TELLER MACHINES TICKETING',NULL,'integer','ELECTRONIC','C',3,0,NULL,'unit',NULL,NULL,NULL),
('AUDITORIUM','DRAFT','AUDITORIUM','AUDITORIUM',NULL,'integer','ELECTRONIC','F',27,0,NULL,'LOCATION',NULL,NULL,NULL),
('BALCONY_TERRACE','DRAFT','BALCONY_TERRACE','BALCONY, TERRACES, LANAI',NULL,'decimal','ACCESSORIES','BALCONY,TERRACES AND LANAI',0,0,NULL,'area in sq.meters','J201',NULL,NULL),
('BANK_AND_RECORD_VAULT','DRAFT','BANK_AND_RECORD_VAULT','BANK AND RECORD VAULT',NULL,'decimal','ACCESSORIES','BANK AND RECORD VAULTS',2,0,NULL,'volume in cu.meter','J305',NULL,NULL),
('BARRIER_CONTROL','DRAFT','BARRIER_CONTROL','BARRIER CONTROLS',NULL,'integer','ELECTRONIC','E',17,0,NULL,'TERMINATION',NULL,NULL,NULL),
('BAR_SINK','DRAFT','BAR_SINK','BAR SINK',NULL,'integer','PLUMBING','SPECIAL',19,0,NULL,'unit',NULL,NULL,NULL),
('BATH_TUB','DRAFT','BATH_TUB','BATH TUB',NULL,'integer','PLUMBING','SPECIAL',12,0,NULL,'unit',NULL,NULL,NULL),
('BIDET','DRAFT','BIDET','BIDET',NULL,'integer','PLUMBING','SPECIAL',15,0,NULL,'unit',NULL,NULL,NULL),
('BOILER','DRAFT','BOILER','BOILER',NULL,'decimal','MECHANICAL','BOILERS',30,0,NULL,'KW',NULL,NULL,NULL),
('BROADCASTING_SYSTEM','DRAFT','BROADCASTING_SYSTEM','BROADCASTING SYSTEM',NULL,'integer','ELECTRONIC','B',2,0,NULL,'LOCATION',NULL,NULL,NULL),
('BUILDING_AUTOMATION_MANAGEMENT_SYSTEM','DRAFT','BUILDING_AUTOMATION_MANAGEMENT_SYSTEM','BUILDING AUTOMATION MANAGEMENT SYSTEMS',NULL,'integer','ELECTRONIC','E',24,0,NULL,'TERMINATION',NULL,NULL,NULL),
('CABLE_CAR','DRAFT','CABLE_CAR','CABLE CAR (KW)',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALKS',15,0,NULL,'KW',NULL,NULL,NULL),
('CABLE_CAR_LINEAL','DRAFT','CABLE_CAR_LINEAL','CABLE CAR LINEAL METER',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALKS',15,0,NULL,'LM',NULL,NULL,NULL),
('CAR_ELEVATOR','DRAFT','CAR_ELEVATOR','CAR ELEVATOR',NULL,'integer','MECHANICAL','ELEVATORS',24,0,NULL,'unit',NULL,NULL,NULL),
('CCTV','DRAFT','CCTV','CATV/MATV/CCTV AND OFF-AIR TELEVISION',NULL,'integer','ELECTRONIC','E',21,0,NULL,'TERMINATION',NULL,NULL,NULL),
('CENTRAILIZED_AIRCON','DRAFT','CENTRAILIZED_AIRCON','CENTRALIZED AIRCONDITION',NULL,'decimal','MECHANICAL','REFRIGERATION,AIR CONDITIONING AND MECHANICAL VENTILATION',4,0,NULL,'TON',NULL,NULL,NULL),
('CENTRALIZED_CLOCK_SYSTEM','DRAFT','CENTRALIZED_CLOCK_SYSTEM','CENTRALIZED_CLOCK_SYSTEM',NULL,'integer','ELECTRONIC','E',25,0,NULL,'TERMINATION',NULL,NULL,NULL),
('CFEI_NUM_AND_SIZE_GROUNDING_WIRE','DRAFT','CFEI_NUM_AND_SIZE_GROUNDING_WIRE','No. and size of grounding wire',NULL,'string','FINAL_ELECTRICAL_INSPECTION','TYPE OF SERVICE',8,0,'[:]',NULL,NULL,NULL,NULL),
('CFEI_NUM_AND_SIZE_OF_WIRE_PHASE','DRAFT','CFEI_NUM_AND_SIZE_OF_WIRE_PHASE','No. of Size of wire/Phase',NULL,'string','FINAL_ELECTRICAL_INSPECTION','TYPE OF SERVICE',7,0,NULL,NULL,NULL,NULL,NULL),
('CFEI_PHASE','DRAFT','CFEI_PHASE','Phase',NULL,'string','FINAL_ELECTRICAL_INSPECTION','TYPE OF SERVICE',9,0,'[:]',NULL,NULL,NULL,NULL),
('CFEI_TOTAL_CONNECTED_LOAD','DRAFT','CFEI_TOTAL_CONNECTED_LOAD','Total Connected Load',NULL,'decimal','FINAL_ELECTRICAL_INSPECTION',NULL,0,0,NULL,'KVA',NULL,NULL,NULL),
('CFEI_TOTAL_GENERATOR_UPS_CAPACITY','DRAFT','CFEI_TOTAL_GENERATOR_UPS_CAPACITY','Total Generator/UPS Capacity',NULL,'decimal','FINAL_ELECTRICAL_INSPECTION',NULL,1,0,NULL,'KVA',NULL,NULL,NULL),
('CFEI_TOTAL_TRANSFORMER_CAPACITY','DRAFT','CFEI_TOTAL_TRANSFORMER_CAPACITY','Total Transformer Capacity',NULL,'decimal','FINAL_ELECTRICAL_INSPECTION',NULL,1,0,NULL,'KVA',NULL,NULL,NULL),
('CFEI_TYPE_OF_INSTALLATION','DRAFT','CFEI_TYPE_OF_INSTALLATION','Type of Installation',NULL,'array','FINAL_ELECTRICAL_INSPECTION','TYPE OF INSTALLATION',2,0,'[\"NEW\",\"SEPARATION OF SERVICE ENTRANCE\",\"ALTERATION/UPGRADING\"]',NULL,NULL,NULL,1),
('CFEI_TYPE_OF_INSTALLATION_OTHERS','DRAFT','CFEI_TYPE_OF_INSTALLATION_OTHERS','Type of Installation (Others)',NULL,'string','FINAL_ELECTRICAL_INSPECTION','TYPE OF INSTALLATION',8,0,NULL,NULL,NULL,NULL,NULL),
('CFEI_TYPE_OF_WIRING','DRAFT','CFEI_TYPE_OF_WIRING','Type of wiring',NULL,'array','FINAL_ELECTRICAL_INSPECTION','TYPE OF WIRING',4,0,'[\"ALTERATION\",\"CONDUITS\",\"ARMORED CABLE\",\"CABLE\",\"RACEWAYS\",\"OPEN WIRING\"]',NULL,NULL,NULL,1),
('CFEI_TYPE_OF_WIRING_OTHERS','DRAFT','CFEI_TYPE_OF_WIRING_OTHERS','Type of wiring ( Others )',NULL,'string','FINAL_ELECTRICAL_INSPECTION','TYPE OF WIRING',5,0,'[:]',NULL,NULL,NULL,NULL),
('CFEI_VOLTAGE','DRAFT','CFEI_VOLTAGE','Voltage',NULL,'decimal','FINAL_ELECTRICAL_INSPECTION','TYPE OF SERVICE',6,0,'[:]','V',NULL,NULL,NULL),
('CHIMNEY','DRAFT','CHIMNEY','CHIMNEY',NULL,'decimal','ACCESSORIES',NULL,11,0,NULL,'height in meters','J202',NULL,NULL),
('CLEARANCE_DURATION','DRAFT','CLEARANCE_DURATION','CLEARANCE DURATION',NULL,'date','HOT_WORKS','INSTRUCTION',2,0,NULL,NULL,NULL,NULL,NULL),
('COIN_CHANGER','DRAFT','COIN_CHANGER','COIN CHANGERS',NULL,'integer','ELECTRONIC','C',6,0,NULL,'unit',NULL,NULL,NULL),
('COLUMBARIUM','DRAFT','COLUMBARIUM','COLUMBARIUM',NULL,'decimal','ACCESSORIES','CEMETERIES',19,0,NULL,'area in sq.meters','J303',NULL,NULL),
('COMPRESSED_AIR_VACUUM','DRAFT','COMPRESSED_AIR_VACUUM','COMPRESSED AIR VACUUM INST. OR INDUSTRIAL GAS',NULL,'integer','MECHANICAL','OTHERS',45,0,NULL,'OUTLET',NULL,NULL,NULL),
('CONCRETE_FRAMING','DRAFT','CONCRETE_FRAMING','CONCRETE FRAMING',NULL,'boolean','CIVIL_STRUCTURAL',NULL,7,0,NULL,'unit',NULL,NULL,NULL),
('CONCRETE_OR_STEEL_TANK','DRAFT','CONCRETE_OR_STEEL_TANK','REINFORCED CONCRETE OR STEEL TANK',NULL,'decimal','ACCESSORIES',NULL,20,0,NULL,'volume in cu.meter','J205',NULL,NULL),
('CONCRETE_OR_STEEL_TANK_UNDERGROUND','DRAFT','CONCRETE_OR_STEEL_TANK_UNDERGROUND','CONCRETE OR STEEL TANK (UNDERGROUND)',NULL,'decimal','ACCESSORIES',NULL,21,0,NULL,'volume in cu.meter','J205',NULL,NULL),
('CONSTRUCTION_ELEVATOR','DRAFT','CONSTRUCTION_ELEVATOR','CONSTRUCTION ELEVATOR (FOR MATERIALS)',NULL,'integer','MECHANICAL','ELEVATORS',21,0,NULL,'unit',NULL,NULL,NULL),
('CORRIDORS','DRAFT','CORRIDORS','CORRIDORS',NULL,'boolean','ARCHITECTURAL','A',3,0,NULL,'UNIT',NULL,NULL,NULL),
('DENTAL_CUSPIDOR','DRAFT','DENTAL_CUSPIDOR','DENTAL CUSPIDOR',NULL,'integer','PLUMBING','SPECIAL',16,0,NULL,'unit',NULL,NULL,NULL),
('DIESEL_GASOLINE_ENGINE','DRAFT','DIESEL_GASOLINE_ENGINE','DIESEL/GASOLINE ENGINE',NULL,'decimal','MECHANICAL','OTHERS',44,0,NULL,'KW',NULL,NULL,NULL),
('DISTANCE_TO_FIRE_EXITS','DRAFT','DISTANCE_TO_FIRE_EXITS','DISTANCE TO FIRE EXITS',NULL,'decimal','ARCHITECTURAL','C',21,0,NULL,'UNIT',NULL,NULL,NULL),
('DOORS_ENTRANCE_THRESHOLDS','DRAFT','DOORS_ENTRANCE_THRESHOLDS','DOORS, ENTRANCES AND THRESHOLDS',NULL,'boolean','ARCHITECTURAL','A',4,0,NULL,'UNIT',NULL,NULL,NULL),
('DRINKING_FOUNTAIN','DRAFT','DRINKING_FOUNTAIN','DRINKING FOUNTAIN',NULL,'integer','PLUMBING','SPECIAL',18,0,NULL,'unit',NULL,NULL,NULL),
('DRINKING_FOUNTAINS','DRAFT','DRINKING_FOUNTAINS','DRINKING FOUNTAINS',NULL,'boolean','ARCHITECTURAL','A',13,0,NULL,'UNIT',NULL,NULL,NULL),
('DUMBWAITER','DRAFT','DUMBWAITER','DUMBWAITER',NULL,'integer','MECHANICAL','ELEVATORS',20,0,NULL,'unit',NULL,NULL,NULL),
('ELECTRIC_METER','DRAFT','ELECTRIC_METER','ELECTRIC METER',NULL,'integer','ELECTRICAL','MISCELLANEOUS',6,0,NULL,'unit',NULL,NULL,NULL),
('ELECTRONIC_CONVEYANCE_SYSTEM','DRAFT','ELECTRONIC_CONVEYANCE_SYSTEM','ELECTRONICALLY-CONTROLLED CONVEYENCE SYSTEMS',NULL,'integer','ELECTRONIC','E',22,0,NULL,'TERMINATION',NULL,NULL,NULL),
('ELECTRONIC_FIRE_ALARM_SYSTEM','DRAFT','ELECTRONIC_FIRE_ALARM_SYSTEM','ELECTRONIC FIRE ALARM',NULL,'integer','ELECTRONIC','E',19,0,NULL,'TERMINATION',NULL,NULL,NULL),
('ELECTRONIC_POLE','DRAFT','ELECTRONIC_POLE','POLES',NULL,'integer','ELECTRONIC','I',31,0,NULL,'POLE',NULL,NULL,NULL),
('ELECTRONIC_POLE_ATTACHMENT','DRAFT','ELECTRONIC_POLE_ATTACHMENT','POLE ATTACHMENT',NULL,'integer','ELECTRONIC','I',32,0,NULL,'ATTACHMENT',NULL,NULL,NULL),
('ELECTRONIC_PROCESS_CONTROL_SYSTEM','DRAFT','ELECTRONIC_PROCESS_CONTROL_SYSTEM','ELECTRONIC PROCESS CONTROL SYSTEM',NULL,'integer','ELECTRONIC','E',23,0,NULL,'TERMINATION',NULL,NULL,NULL),
('ELECTRONIC_SIGNAGE','DRAFT','ELECTRONIC_SIGNAGE','ELECTRONIC INDOOR AND OUTDOOR SIGNAGES AND DISPLAY SYSTEMS',NULL,'integer','ELECTRONIC','H',30,0,NULL,'unit',NULL,NULL,NULL),
('EMERGENCY_LIGHTS','DRAFT','EMERGENCY_LIGHTS','EMERGENCY LIGHTS',NULL,'integer','ARCHITECTURAL','C',26,0,NULL,'UNIT',NULL,NULL,NULL),
('ENCROACHMENT_FOOTING','DRAFT','ENCROACHMENT_FOOTING','ENCROACHMENT OF FOOTINGS OR FOUNDATIONS OF BLDGS',NULL,'decimal','CIVIL_STRUCTURAL',NULL,5,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('ENGINE_NON_LTO','DRAFT','ENGINE_NON_LTO','OTHER INTERNAL COMBUSTION ENGINE (CRANE, FORKLIFT,ETC)',NULL,'decimal','MECHANICAL','OTHERS',48,0,NULL,'KW',NULL,NULL,NULL),
('ERECTION','DRAFT','ERECTION','ERECTION/LIFTING',NULL,'boolean','CIVIL_STRUCTURAL',NULL,6,0,NULL,'unit',NULL,NULL,NULL),
('ESCALATOR','DRAFT','ESCALATOR','ESCALATOR AND MOVING WALK (KW)',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALKS',10,0,NULL,'KW',NULL,NULL,NULL),
('ESCALATOR_LINEAL','DRAFT','ESCALATOR_LINEAL','ESCALATOR AND MOVING WALK (LINEAL METER)',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALKS',11,0,NULL,'LM',NULL,NULL,NULL),
('EXCAVATION','DRAFT','EXCAVATION','EXCAVATION',NULL,'decimal','CIVIL_STRUCTURAL',NULL,2,0,NULL,'volume in cu.meter',NULL,NULL,NULL),
('EXCAVATION_BASEMENT','DRAFT','EXCAVATION_BASEMENT','EXCAVATION FOR FOUNDATION WITH BASEMENT',NULL,'decimal','EXCAVATION','GROUND PREPARATION AND EXCAVATION',3,0,NULL,'volume in cu.meter',NULL,NULL,NULL),
('EXCAVATION_NON_BASEMENT','DRAFT','EXCAVATION_NON_BASEMENT','EXCAVATION OTHER THAN FOUNDATION OR BASEMENT',NULL,'decimal','EXCAVATION','GROUND PREPARATION AND EXCAVATION',4,0,NULL,'volume in cu.meter',NULL,NULL,NULL),
('FAUCET','DRAFT','FAUCET','FAUCET',NULL,'integer','PLUMBING','GENERAL',6,0,NULL,'unit',NULL,NULL,NULL),
('FENCE_MADE_OF_INDIGENOUS_MATERIAL','DRAFT','FENCE_MADE_OF_INDIGENOUS_MATERIAL','FENCE MADE OF INDIGENOUS MATERIAL,BARBED,CHICKEN OR HOG WIRE',NULL,'decimal','FENCING','FENCING',3,0,NULL,'LM',NULL,NULL,NULL),
('FENCE_MADE_OF_MASONRY_METAL_UPTO_1_8_M','DRAFT','FENCE_MADE_OF_MASONRY_METAL_UPTO_1_8_M','FENCE MADE OF MASONRY OR METAL UP TO 1.8 METER IN HEIGHT',NULL,'decimal','FENCING','FENCING',1,0,NULL,'LM',NULL,NULL,NULL),
('FENCE_MADE_OF_MASONRY_OR_METAL_ABOVE_1_8_M','DRAFT','FENCE_MADE_OF_MASONRY_OR_METAL_ABOVE_1_8_M','FENCE MADE OF MASONRY OR METAL MORE THAN 1.8 METER IN HEIGHT',NULL,'decimal','FENCING','FENCING',2,0,NULL,'LNM',NULL,NULL,NULL),
('FIREWALL','DRAFT','FIREWALL','FIREWALL (SEPARATE FROM BUILDING)',NULL,'decimal','FENCING','FENCING',6,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('FIRE_ALARM_COST','DRAFT','FIRE_ALARM_COST','FIRE ALARM COST',NULL,'decimal','BFP_SALES_TAX',NULL,1,0,NULL,'COST',NULL,NULL,NULL),
('FIRE_FIGHTING_AND_SAFETY_FACILITIES','DRAFT','FIRE_FIGHTING_AND_SAFETY_FACILITIES','FIRE FIGHTING AND SAFETY FACILITIES',NULL,'integer','ARCHITECTURAL','C',24,0,NULL,'UNIT',NULL,NULL,NULL),
('FIRE_SPRINKLER','DRAFT','FIRE_SPRINKLER','AUTOMATIC FIRE SPRINKLER',NULL,'integer','MECHANICAL','OTHERS',43,0,NULL,'HEAD',NULL,NULL,NULL),
('FIRE_SUPP_COST','DRAFT','FIRE_SUPP_COST','AUTOMATIC KITCHEN HOOD FIRE SUPPRESSION COST',NULL,'decimal','BFP_SALES_TAX',NULL,4,0,NULL,'COST',NULL,NULL,NULL),
('FIRE_WALLS','DRAFT','FIRE_WALLS','FIRE WALLS',NULL,'integer','ARCHITECTURAL','C',23,0,NULL,'UNIT',NULL,NULL,NULL),
('FIXED_OVEN','DRAFT','FIXED_OVEN','COMMERCIAL/INDUSTRIAL FIXED OVEN',NULL,'decimal','ACCESSORIES','OVEN',12,0,NULL,'area in sq.meters','J202',NULL,NULL),
('FIXED_TYPE_STERILIZER','DRAFT','FIXED_TYPE_STERILIZER','FIXED TYPE STERILIZER',NULL,'integer','PLUMBING','SPECIAL',22,0,NULL,'unit',NULL,NULL,NULL),
('FLOOR_DRAIN','DRAFT','FLOOR_DRAIN','FLOOR DRAIN',NULL,'integer','PLUMBING','GENERAL',3,0,NULL,'unit',NULL,NULL,NULL),
('FLOOR_FINISHES','DRAFT','FLOOR_FINISHES','FLOOR FINISHES',NULL,'boolean','ARCHITECTURAL','A',12,0,NULL,'UNIT',NULL,NULL,NULL),
('FOUNDATION','DRAFT','FOUNDATION','FOUNDATION',NULL,'boolean','CIVIL_STRUCTURAL',NULL,5,0,NULL,'unit',NULL,NULL,NULL),
('FREIGHT_ELEVATOR','DRAFT','FREIGHT_ELEVATOR','FREIGHT ELEVATOR',NULL,'integer','MECHANICAL','ELEVATORS',23,0,NULL,'unit',NULL,NULL,NULL),
('FUNICULAR','DRAFT','FUNICULAR','FUNICULAR (KW)',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALKS',14,0,NULL,'KW',NULL,NULL,NULL),
('FUNICULAR_LINEAL','DRAFT','FUNICULAR_LINEAL','FUNICULAR (LINEAL METER)',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALS',14,0,NULL,'LM',NULL,NULL,NULL),
('GARAGE_TRAP','DRAFT','GARAGE_TRAP','GARAGE TRAP',NULL,'integer','PLUMBING','SPECIAL',14,0,NULL,'unit',NULL,NULL,NULL),
('GAS_FIRED_WATER_HEATER','DRAFT','GAS_FIRED_WATER_HEATER','GAS FIRED WATER HEATER',NULL,'integer','PLUMBING','SPECIAL',17,0,NULL,'unit',NULL,NULL,NULL),
('GAS_METER','DRAFT','GAS_METER','GAS METER',NULL,'integer','MECHANICAL','OTHERS',50,0,NULL,'unit',NULL,NULL,NULL),
('GREASE_TRAP','DRAFT','GREASE_TRAP','GREASE TRAP',NULL,'integer','PLUMBING','SPECIAL',13,0,NULL,'unit',NULL,NULL,NULL),
('GUYING_ATTACHMENT','DRAFT','GUYING_ATTACHMENT','GUYING ATTACHMENT',NULL,'integer','ELECTRICAL','POLE/ATTACHMENT LOCATION PLAN PERMIT',5,0,NULL,'ATTACHMENT',NULL,NULL,NULL),
('HANDRAILS','DRAFT','HANDRAILS','HANDRAILS',NULL,'boolean','ARCHITECTURAL','A',10,0,NULL,'UNIT',NULL,NULL,NULL),
('HW_WATCHMAN1','DRAFT','HW_WATCHMAN1','WATCHMAN 1',NULL,'string','HOT_WORKS','INSTRUCTION',20,0,NULL,NULL,NULL,NULL,NULL),
('HW_WATCHMAN2','DRAFT','HW_WATCHMAN2','WATCHMAN 2',NULL,'string','HOT_WORKS','INSTRUCTION',22,0,NULL,NULL,NULL,NULL,NULL),
('HW_WATCHMAN3','DRAFT','HW_WATCHMAN3','WATCHMAN 3',NULL,'string','HOT_WORKS','INSTRUCTION',23,0,NULL,NULL,NULL,NULL,NULL),
('HW_WORKER1','DRAFT','HW_WORKER1','HOT WORKS - WORKER 1',NULL,'string','HOT_WORKS','INSTRUCTION',11,0,NULL,NULL,NULL,NULL,NULL),
('HW_WORKER2','DRAFT','HW_WORKER2','HOT WORKS - WORKER 2',NULL,'string','HOT_WORKS','INSTRUCTION',12,0,NULL,NULL,NULL,NULL,NULL),
('HW_WORKER3','DRAFT','HW_WORKER3','HOT WORKS - WORKER 3',NULL,'string','HOT_WORKS','INSTRUCTION',12,0,NULL,NULL,NULL,NULL,NULL),
('HYDRO_NUCLEAR_SOLAR_GEN_UNIT','DRAFT','HYDRO_NUCLEAR_SOLAR_GEN_UNIT','HYDRO NUCLEAR OR SOLAR GENERATING UNIT',NULL,'decimal','MECHANICAL','OTHERS',44,0,NULL,'KW',NULL,NULL,NULL),
('ICE_PLANT','DRAFT','ICE_PLANT','ICE PLANT',NULL,'decimal','MECHANICAL','REFRIGERATION,AIR CONDITIONING AND MECHANICAL VENTILATION',2,0,NULL,'TON',NULL,NULL,NULL),
('ILLUMINATED_ADVERTISING_SIGN','DRAFT','ILLUMINATED_ADVERTISING_SIGN','ILLUMINATED ADVERTISING SIGN',NULL,'decimal','SIGN','SIGNAGE',4,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('ILLUMINATED_BUSINESS_SIGN','DRAFT','ILLUMINATED_BUSINESS_SIGN','ILLUMINATED BUSINESS SIGN',NULL,'decimal','SIGN','SIGNAGE',3,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('INFORMATION_TECHNOLOGY_SYSTEM','DRAFT','INFORMATION_TECHNOLOGY_SYSTEM','INFORMATION TECHNOLOGY SYSTEM (WORKSTATION,SERVER,ROUTER)',NULL,'integer','ELECTRONIC','D',12,0,NULL,'OUTLET',NULL,NULL,NULL),
('JOBNO','DRAFT','JOBNO','Job No.',NULL,'string','HOT_WORKS','INSTRUCTION',0,0,NULL,NULL,NULL,NULL,NULL),
('KILN_FURNACE','DRAFT','KILN_FURNACE','INDUSTRIAL KILN/FURNACE',NULL,'decimal','ACCESSORIES','OVEN',13,0,NULL,'volume in cu.meter','J202',NULL,NULL),
('KITCHEN_SINK','DRAFT','KITCHEN_SINK','KITCHEN SINK',NULL,'integer','PLUMBING','GENERAL',10,0,NULL,'unit',NULL,NULL,NULL),
('LAB_SINK','DRAFT','LAB_SINK','LABORATORY SINK',NULL,'integer','PLUMBING','SPECIAL',21,0,NULL,'unit',NULL,NULL,NULL),
('LAUNDRY_SINK','DRAFT','LAUNDRY_SINK','LAUNDRY SINK',NULL,'integer','PLUMBING','SPECIAL',20,0,NULL,'unit',NULL,NULL,NULL),
('LAUNDRY_TRAY','DRAFT','LAUNDRY_TRAY','LAUNDRY TRAY',NULL,'integer','PLUMBING','SPECIAL',20,0,NULL,'unit',NULL,NULL,NULL),
('LAVATORY','DRAFT','LAVATORY','LAVATORY',NULL,'integer','PLUMBING','GENERAL',5,0,NULL,'unit',NULL,NULL,NULL),
('LIFTS_ELEVATORS','DRAFT','LIFTS_ELEVATORS','LIFTS / ELEVATORS',NULL,'boolean','ARCHITECTURAL','A',6,0,NULL,'UNIT',NULL,NULL,NULL),
('LIGHTING_CONTROL','DRAFT','LIGHTING_CONTROL','LIGHTING CONTROLS',NULL,'integer','ELECTRONIC','E',14,0,NULL,'TERMINATION',NULL,NULL,NULL),
('LINE_AND_GRADE','DRAFT','LINE_AND_GRADE','LINE AND GRADE',NULL,'decimal','LINE_AND_GRADE',NULL,1,0,NULL,'M',NULL,NULL,NULL),
('LOCATION_FINDING_SYSTEM','DRAFT','LOCATION_FINDING_SYSTEM','LOCATION OR DIRECTION-FINDING SYSTEMS',NULL,'integer','ELECTRONIC','C',7,0,NULL,'unit',NULL,NULL,NULL),
('LPG_PIPING_COST','DRAFT','LPG_PIPING_COST','LPG PIPING COST',NULL,'decimal','BFP_SALES_TAX',NULL,3,0,NULL,'COST',NULL,NULL,NULL),
('MATERIAL_TESTING','DRAFT','MATERIAL_TESTING','MATERIAL TESTING',NULL,'boolean','CIVIL_STRUCTURAL',NULL,12,0,NULL,'unit',NULL,NULL,NULL),
('MECHANICAL_VENTILATION','DRAFT','MECHANICAL_VENTILATION','MECHANICAL VENTILATION (BLOWER, FAN)',NULL,'decimal','MECHANICAL','REFRIGERATION,AIR CONDITIONING AND MECHANICAL VENTILATION',6,0,NULL,'KW',NULL,NULL,NULL),
('MEDICAL_ELECTRONIC_EQUIPMENT','DRAFT','MEDICAL_ELECTRONIC_EQUIPMENT','ELECTRONIC EQUIPMENT USED FOR MEDICAL (ULTRASOUND AND LAB TESTING) ',NULL,'integer','ELECTRONIC','C',11,0,NULL,'unit',NULL,NULL,NULL),
('MOVING_WALK','DRAFT','MOVING_WALK','MOVING WALK',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALKS',12,0,NULL,'KW',NULL,NULL,NULL),
('MOVING_WALK_20LM','DRAFT','MOVING_WALK_20LM','MOVING WALK (20 LINEAL METERS OR LESS)',NULL,'decimal','MECHANICAL','ESCALATORS AND MOVING WALKS',13,0,NULL,'KW',NULL,NULL,NULL),
('NAVIGATIONAL_EQUIPMENT','DRAFT','NAVIGATIONAL_EQUIPMENT','NAVIGATIONAL EQUIPMENT USED FOR LAND,AERONAUTICAL OR MARITIME APPLICATIONS',NULL,'integer','ELECTRONIC','C',8,0,NULL,'unit',NULL,NULL,NULL),
('NEON_ADVERTISING_SIGN','DRAFT','NEON_ADVERTISING_SIGN','NEON ADVERTISING SIGN',NULL,'decimal','SIGN','SIGNAGE',2,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('NEON_BUSINESS_SIGN','DRAFT','NEON_BUSINESS_SIGN','NEON BUSINESS SIGN',NULL,'decimal','SIGN','SIGNAGE',1,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('NUMBER_AND_WIDTH_OF_EXIT_DOORS','DRAFT','NUMBER_AND_WIDTH_OF_EXIT_DOORS','NUMBER AND WIDTH OF EXIT DOORS',NULL,'integer','ARCHITECTURAL','C',19,0,NULL,'UNIT',NULL,NULL,NULL),
('OTHER_ADVERTISING_SIGN','DRAFT','OTHER_ADVERTISING_SIGN','OTHER ADVERTISING SIGN',NULL,'decimal','SIGN','SIGNAGE',8,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('OTHER_BUSINESS_SIGN','DRAFT','OTHER_BUSINESS_SIGN','OTHER BUSINESS SIGN',NULL,'decimal','SIGN','SIGNAGE',7,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('OTHER_ELECTRONIC_EQUIPMENT','DRAFT','OTHER_ELECTRONIC_EQUIPMENT','OTHER TYPES OR ELECTRONICS OR ELECTRONICALLY-CONTROLLED EQUIPMENT',NULL,'integer','ELECTRONIC','J',33,0,NULL,'unit',NULL,NULL,NULL),
('OTHER_MACHINERY_EQUIPMENT','DRAFT','OTHER_MACHINERY_EQUIPMENT','OTHER MACHINERY/EQUIPMENT',NULL,'decimal','MECHANICAL','OTHERS',50,0,NULL,'volume in cu.meter',NULL,NULL,NULL),
('PACKAGED_SPLIT_TYPE_AIRCON','DRAFT','PACKAGED_SPLIT_TYPE_AIRCON','PACKAGED/SPLIT TYPE AIRCONDITIONG',NULL,'decimal','MECHANICAL','REFRIGERATION,AIR CONDITIONING AND MECHANICAL VENTILATION',3,0,NULL,'TON',NULL,NULL,NULL),
('PAINTEDON_ADVERTISING_SIGN','DRAFT','PAINTEDON_ADVERTISING_SIGN','PAINTED-ON ADVERTISING SIGN',NULL,'decimal','SIGN','SIGNAGE',6,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('PAINTEDON_BUSINESS_SIGN','DRAFT','PAINTEDON_BUSINESS_SIGN','PAINTED-ON BUSINESS SIGN',NULL,'decimal','SIGN','SIGNAGE',5,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('PARKING_AREAS','DRAFT','PARKING_AREAS','PARKING AREAS',NULL,'integer','ARCHITECTURAL','A',8,0,NULL,'SLOTS',NULL,NULL,NULL),
('PARKING_MANAGEMENT_SYSTEM','DRAFT','PARKING_MANAGEMENT_SYSTEM','PARKING MANAGEMENT SYSTEM',NULL,'integer','ELECTRONIC','E',16,0,NULL,'TERMINATION',NULL,NULL,NULL),
('PASSENGER_ELEVATOR','DRAFT','PASSENGER_ELEVATOR','PASSENGER ELEVATOR',NULL,'integer','MECHANICAL','ELEVATORS',22,0,NULL,'unit',NULL,NULL,NULL),
('PERCENTAGE_BUILDING_FOOTPRINT','DRAFT','PERCENTAGE_BUILDING_FOOTPRINT','PERCENTAGE OF BUILDING FOOTPRINT',NULL,'decimal','ARCHITECTURAL','B',16,0,NULL,'%',NULL,NULL,NULL),
('PERCENTAGE_IMPERVIOUS_SURFACE_AREA','DRAFT','PERCENTAGE_IMPERVIOUS_SURFACE_AREA','PERCENTAGE OF IMPERVIOUS SURFACE AREA',NULL,'decimal','ARCHITECTURAL','B',17,0,NULL,'%',NULL,NULL,NULL),
('PERCENTAGE_UNPAVED_SURFACE_AREA','DRAFT','PERCENTAGE_UNPAVED_SURFACE_AREA','PERCENTAGE OF UNPAVED SURFACE AREA',NULL,'decimal','ARCHITECTURAL','B',18,0,NULL,'%',NULL,NULL,NULL),
('PHOTO_REPRODUCTION_MACHINE','DRAFT','PHOTO_REPRODUCTION_MACHINE','PHOTOGRAPHY AND REPRODUCTION MACHINES',NULL,'integer','ELECTRONIC','C',9,0,NULL,'unit',NULL,NULL,NULL),
('PILING_WORKS','DRAFT','PILING_WORKS','PILING WORKS',NULL,'boolean','CIVIL_STRUCTURAL',NULL,4,0,NULL,'unit',NULL,NULL,NULL),
('PNEUMATIC_TUBE_CONVEYOR_MONORAIL','DRAFT','PNEUMATIC_TUBE_CONVEYOR_MONORAIL','PNEUMATIC TUBES, CONVEYORS AND MONORAILS',NULL,'decimal','MECHANICAL','OTHERS',51,0,NULL,'LM',NULL,NULL,NULL),
('POWER_PIPING_CUBIC','DRAFT','POWER_PIPING_CUBIC','POWER PIPING (CUBIC)',NULL,'decimal','MECHANICAL','OTHERS',47,0,NULL,'volume in cu.meter',NULL,NULL,NULL),
('POWER_PIPING_LINEAL','DRAFT','POWER_PIPING_LINEAL','POWER PIPING (LINEAL METER)',NULL,'decimal','MECHANICAL','OTHERS',46,0,NULL,'LM',NULL,NULL,NULL),
('POWER_SUPPLY_POLE_LOCATION','DRAFT','POWER_SUPPLY_POLE_LOCATION','POWER SUPPLY POLE LOCATION',NULL,'integer','ELECTRICAL','POLE/ATTACHMENT LOCATION PLAN PERMIT',4,0,NULL,'POLE',NULL,NULL,NULL),
('PRESSURE_VESSEL','DRAFT','PRESSURE_VESSEL','PRESSURE VESSEL',NULL,'decimal','MECHANICAL','OTHERS',49,0,NULL,'volume in cu.meter',NULL,NULL,NULL),
('PRESSURIZED_WATER_HEATER','DRAFT','PRESSURIZED_WATER_HEATER','PRESSURIZED WATER HEATER',NULL,'integer','MECHANICAL','OTHERS',40,0,NULL,'unit',NULL,NULL,NULL),
('PRESTRESS_WORKS','DRAFT','PRESTRESS_WORKS','PRESTRESS WORKS',NULL,'boolean','CIVIL_STRUCTURAL',NULL,11,0,NULL,'unit',NULL,NULL,NULL),
('PUBLIC_TELEPHONES','DRAFT','PUBLIC_TELEPHONES','PUBLIC TELEPHONES',NULL,'boolean','ARCHITECTURAL','A',14,0,NULL,'UNIT',NULL,NULL,NULL),
('PUMP','DRAFT','PUMP','PUMP',NULL,'decimal','MECHANICAL','OTHERS',42,0,NULL,'KW',NULL,NULL,NULL),
('RAMPS','DRAFT','RAMPS','RAMPS',NULL,'integer','ARCHITECTURAL','A',7,0,NULL,'SLOTS',NULL,NULL,NULL),
('REFRIGERATION','DRAFT','REFRIGERATION','REFRIGERATION (COLD STORAGE)',NULL,'decimal','MECHANICAL','REFRIGERATION,AIR CONDITIONING AND MECHANICAL VENTILATION',1,0,NULL,'TON',NULL,NULL,NULL),
('SCAFFOLDING','DRAFT','SCAFFOLDING','SCAFFOLDING',NULL,'decimal','SCAFFOLDING','SCAFFOLDING',1,0,NULL,'LM',NULL,NULL,NULL),
('SEATING_ACCOMODATIONS','DRAFT','SEATING_ACCOMODATIONS','SEATING ACCOMODATIONS',NULL,'boolean','ARCHITECTURAL','A',15,0,NULL,'UNIT',NULL,NULL,NULL),
('SECURITY_ALARM_SYSTEM','DRAFT','SECURITY_ALARM_SYSTEM','SECURITY AND ALARM SYSTEMS',NULL,'integer','ELECTRONIC','E',13,0,NULL,'TERMINATION',NULL,NULL,NULL),
('SEMI_ENCLOSED_MAUSOLEUM','DRAFT','SEMI_ENCLOSED_MAUSOLEUM','SEMI-ENCLOSED MAUSOLEUM','Canopied or not, per sqm of built up area','decimal','ACCESSORIES','CEMETERIES',17,0,NULL,'area in sq.meters','J303',NULL,NULL),
('SEPTIC_TANK','DRAFT','SEPTIC_TANK','SEPTIC TANK',NULL,'decimal','PLUMBING','OTHERS',40,0,NULL,'volume in cu.meter',NULL,NULL,NULL),
('SEWAGE_PUMP','DRAFT','SEWAGE_PUMP','SEWAGE PUMP',NULL,'decimal','MECHANICAL','OTHERS',41,0,NULL,'KW',NULL,NULL,NULL),
('SHOWER_HEAD','DRAFT','SHOWER_HEAD','SHOWER HEAD',NULL,'integer','PLUMBING','GENERAL',7,0,NULL,'unit',NULL,NULL,NULL),
('SIGNAGE_ERECTION_AND_ANCHORAGE_OF_DISPLAY_SURFACE','DRAFT','SIGNAGE_ERECTION_AND_ANCHORAGE_OF_DISPLAY_SURFACE','ERECTION AND ANCHORAGE OF DISPLAY SURFACE',NULL,'decimal','SIGN',NULL,0,0,NULL,'area in sq.meters',NULL,NULL,NULL),
('SIGNAL_LIGHT','DRAFT','SIGNAL_LIGHT','SIGNAL LIGHTS',NULL,'integer','ELECTRONIC','E',18,0,NULL,'TERMINATION',NULL,NULL,NULL),
('SINK','DRAFT','SINK','SINK',NULL,'integer','PLUMBING','GENERAL',4,0,NULL,'unit',NULL,NULL,NULL),
('SLABS','DRAFT','SLABS','SLABS',NULL,'boolean','CIVIL_STRUCTURAL',NULL,9,0,NULL,'unit',NULL,NULL,NULL),
('SLOP_SINK','DRAFT','SLOP_SINK','SLOP SINK',NULL,'integer','PLUMBING','SPECIAL',10,0,NULL,'unit',NULL,NULL,NULL),
('SMOKESTACK','DRAFT','SMOKESTACK','SMOKESTACK',NULL,'decimal','ACCESSORIES',NULL,10,0,NULL,'height in meters','J202',NULL,NULL),
('SMOKE_DETECTORS','DRAFT','SMOKE_DETECTORS','SMOKE DETECTORS',NULL,'integer','ARCHITECTURAL','C',25,0,NULL,'UNIT',NULL,NULL,NULL),
('SODA_FOUNTAIN_SINK','DRAFT','SODA_FOUNTAIN_SINK','SODA FOUNTAIN SINK',NULL,'integer','PLUMBING','SPECIAL',19,0,NULL,'unit',NULL,NULL,NULL),
('SOIL_STABILIZATION','DRAFT','SOIL_STABILIZATION','SOIL STABILIZATION',NULL,'boolean','CIVIL_STRUCTURAL',NULL,3,0,NULL,'unit',NULL,NULL,NULL),
('SOUND_COMMUNICATION_SYSTEM','DRAFT','SOUND_COMMUNICATION_SYSTEM','SOUND COMMUNICATION SYSTEMS',NULL,'integer','ELECTRONIC','E',20,0,NULL,'TERMINATION',NULL,NULL,NULL),
('SPRINKLER_COST','DRAFT','SPRINKLER_COST','SPRINKLER COST',NULL,'decimal','BFP_SALES_TAX',NULL,2,0,NULL,'COST',NULL,NULL,NULL),
('STAIRS','DRAFT','STAIRS','STAIRS',NULL,'boolean','ARCHITECTURAL','A',1,0,NULL,'unit',NULL,NULL,NULL),
('STAKING','DRAFT','STAKING','STAKING',NULL,'boolean','CIVIL_STRUCTURAL',NULL,1,0,NULL,'unit',NULL,NULL,NULL),
('STEAM_GAS_TURBINE_ENGINE','DRAFT','STEAM_GAS_TURBINE_ENGINE','STEAM/GAS TURBINE ENGINE',NULL,'decimal','MECHANICAL','OTHERS',44,0,NULL,'KW',NULL,NULL,NULL),
('STEEL_TOWER','DRAFT','STEEL_TOWER','STEEL TOWERS',NULL,'boolean','CIVIL_STRUCTURAL',NULL,13,0,NULL,'unit',NULL,NULL,NULL),
('STORAGE_SILO','DRAFT','STORAGE_SILO','STORAGE SILO',NULL,'decimal','ACCESSORIES',NULL,9,0,NULL,'height in meters','J101',NULL,NULL),
('STRUCTURAL_STEEL_FRAMING','DRAFT','STRUCTURAL_STEEL_FRAMING','STRUCTURAL STEEL FRAMING',NULL,'boolean','CIVIL_STRUCTURAL',NULL,8,0,NULL,'unit',NULL,NULL,NULL),
('STUDIO','DRAFT','STUDIO','STUDIOS (AUDIO,VIDEO PRODUCTION)',NULL,'integer','ELECTRONIC','F',26,0,NULL,'LOCATION',NULL,NULL,NULL),
('SURVEILLANCE_SYSTEM','DRAFT','SURVEILLANCE_SYSTEM','MONITORING AND SURVEILLLANCE SYSTEM',NULL,'integer','ELECTRONIC','E',15,0,NULL,'TERMINATION',NULL,NULL,NULL),
('SWIMMING_POOL','DRAFT','SWIMMING_POOL','SWIMMING POOL',NULL,'decimal','ACCESSORIES',NULL,3,0,NULL,'volume in cu.meter','J203',NULL,NULL),
('SWIMMING_POOL_SHOWER_LOCKER_ROOM','DRAFT','SWIMMING_POOL_SHOWER_LOCKER_ROOM','SWIMMING POOL SHOWER/LOCKER ROOM',NULL,'integer','ACCESSORIES',NULL,5,0,NULL,'unit','J203',NULL,NULL),
('SWIMMING_POOL_USING_INDIGENOUS_MATERIALS','DRAFT','SWIMMING_POOL_USING_INDIGENOUS_MATERIALS','SWIMMING POOL USING INDIGENOUS MATERIALS',NULL,'decimal','ACCESSORIES',NULL,4,0,NULL,'volume in cu.meter','J203',NULL,NULL),
('SWITCH_CONTROL_BUZZERS','DRAFT','SWITCH_CONTROL_BUZZERS','SWITCHES, CONTROLS, BUZZERS',NULL,'boolean','ARCHITECTURAL','A',9,0,NULL,'UNIT',NULL,NULL,NULL),
('TANKS','DRAFT','TANKS','TANKS',NULL,'boolean','CIVIL_STRUCTURAL',NULL,14,0,NULL,'unit',NULL,NULL,NULL),
('TELECOM_SYSTEM','DRAFT','TELECOM_SYSTEM','TELECOMMUNICATION SYSTEM',NULL,'integer','ELECTRONIC','A',1,0,NULL,'PORT',NULL,NULL,NULL),
('TELEPHONE_BOOTH','DRAFT','TELEPHONE_BOOTH','TELEPHONE BOOTHS / PAY PHONE',NULL,'integer','ELECTRONIC','C',5,0,NULL,'unit',NULL,NULL,NULL),
('THEATER','DRAFT','THEATER','THEATER',NULL,'integer','ELECTRONIC','F',28,0,NULL,'LOCATION',NULL,NULL,NULL),
('THRESHOLDS','DRAFT','THRESHOLDS','THRESHOLDS',NULL,'boolean','ARCHITECTURAL','A',11,0,NULL,'UNIT',NULL,NULL,NULL),
('TOMB','DRAFT','TOMB','TOMB','Area per covered ground','decimal','ACCESSORIES','CEMETERIES',16,0,NULL,'area in sq.meters','J303',NULL,NULL),
('TOTALLY_ENCLOSED_MAUSOLEUM','DRAFT','TOTALLY_ENCLOSED_MAUSOLEUM','TOTALLY ENCLOSED MAUSOLEUM',NULL,'decimal','ACCESSORIES','CEMETERIES',18,0,NULL,'area in sq.meters','J303',NULL,NULL),
('TOTAL_CONNECTED_LOAD','DRAFT','TOTAL_CONNECTED_LOAD','TOTAL CONNECTED LOAD',NULL,'decimal','ELECTRICAL','GENERAL',1,0,NULL,'KVA',NULL,NULL,NULL),
('TOTAL_GENERATOR_UPS_CAPACITY','DRAFT','TOTAL_GENERATOR_UPS_CAPACITY','TOTAL GENERATOR/UPS CAPACITY','TGC','decimal','ELECTRICAL','GENERAL',3,0,NULL,'KVA',NULL,NULL,NULL),
('TOTAL_TRANSFORMER_CAPACITY','DRAFT','TOTAL_TRANSFORMER_CAPACITY','TOTAL TRANSFORMER CAPACITY',NULL,'decimal','ELECTRICAL','GENERAL',2,0,NULL,'KVA',NULL,NULL,NULL),
('TOWER_AND_OTHER_STRUCTURE_SELF_SUPPORTING','DRAFT','TOWER_AND_OTHER_STRUCTURE_SELF_SUPPORTING','TOWER AND OTHER STRUCTURES (SELF-SUPPORTING)','TV AND RADIO TOWER, WATER TANK SUPPORTING STRUCTURES','decimal','ACCESSORIES',NULL,7,0,NULL,'height in meters','J202',NULL,NULL),
('TOWER_AND_OTHER_STRUCTURE_TRILON_GUYED','DRAFT','TOWER_AND_OTHER_STRUCTURE_TRILON_GUYED','TOWER AND OTHER STRUCTURE (TRILON GUYED)','TV AND RADIO TOWER, WATER TANK SUPPORTING STRUCTURES','decimal','ACCESSORIES',NULL,8,0,NULL,'height in meters','J202',NULL,NULL),
('URINAL','DRAFT','URINAL','URINAL',NULL,'integer','PLUMBING','SPECIAL',11,0,NULL,'unit',NULL,NULL,NULL),
('VENDING_DISPENSING_MACHINE','DRAFT','VENDING_DISPENSING_MACHINE','VENDING AND OTHER TYPES OF ELECTRONIC DISPENSING MACHINES',NULL,'integer','ELECTRONIC','C',4,0,NULL,'unit',NULL,NULL,NULL),
('WALKWAYS','DRAFT','WALKWAYS','WALKWAYS',NULL,'boolean','ARCHITECTURAL','A',2,0,NULL,'UNIT',NULL,NULL,NULL),
('WALLS','DRAFT','WALLS','WALLS',NULL,'boolean','CIVIL_STRUCTURAL',NULL,10,0,NULL,'unit',NULL,NULL,NULL),
('WASHROOM_AND_TOILETS','DRAFT','WASHROOM_AND_TOILETS','WASH ROOMS AND TOILETS',NULL,'boolean','ARCHITECTURAL','A',5,0,NULL,'UNIT',NULL,NULL,NULL),
('WATER_AND_WASTE_WATER_TREATMENT_TANK','DRAFT','WATER_AND_WASTE_WATER_TREATMENT_TANK','WATER AND WASTE WATER TREATMENT TANK','Incuding Cisterns, Sedimentation, and Chemical Treatment','decimal','ACCESSORIES',NULL,15,0,NULL,'volume in cu.meter','J205',NULL,NULL),
('WATER_CLOSET','DRAFT','WATER_CLOSET','WATER CLOSET',NULL,'integer','PLUMBING','GENERAL',2,0,NULL,'unit',NULL,NULL,NULL),
('WATER_METER','DRAFT','WATER_METER','WATER METER',NULL,'integer','PLUMBING','OTHERS',23,0,NULL,'unit',NULL,NULL,NULL),
('WATER_METER_12_25','DRAFT','WATER_METER_12_25','WATER METER (12-25 mm ├ÿ )',NULL,'integer','PLUMBING','OTHERS',23,0,NULL,'unit',NULL,NULL,NULL),
('WATER_METER_25','DRAFT','WATER_METER_25','WATER METER (ABOVE 25 mm ├ÿ)',NULL,'integer','PLUMBING','OTHERS',31,0,NULL,'unit',NULL,NULL,NULL),
('WATER_SUMP','DRAFT','WATER_SUMP','WATER SUMP',NULL,'decimal','MECHANICAL','OTHERS',41,0,NULL,'KW',NULL,NULL,NULL),
('WELDING_MACHINE','DRAFT','WELDING_MACHINE','WELDING/OXY-ACETYLENE MACHINE',NULL,'integer','HOT_WORKS',NULL,100,0,NULL,'unit',NULL,NULL,NULL),
('WIDTH_OF_CORRIDORS','DRAFT','WIDTH_OF_CORRIDORS','WIDTH OF CORRIDORS',NULL,'decimal','ARCHITECTURAL','C',20,0,NULL,'UNIT',NULL,NULL,NULL),
('WINDOW_TYPE_AIRCON','DRAFT','WINDOW_TYPE_AIRCON','WINDOW TYPE AIRCONDITIONING',NULL,'integer','MECHANICAL','REFRIGERATION,AIR CONDITIONING AND MECHANICAL VENTILATION',5,0,NULL,'EA',NULL,NULL,NULL),
('XRAY_SCANNER','DRAFT','XRAY_SCANNER',' X-RAY SCANNERS',NULL,'integer','ELECTRONIC','C',10,0,NULL,'unit',NULL,NULL,NULL),
('ZONE','DRAFT','ZONE','Zone',NULL,'string','LOCATIONAL_CLEARANCE',NULL,2,0,NULL,NULL,NULL,NULL,NULL),
('ZONECLASS','DRAFT','ZONECLASS','Zone Class',NULL,'lookup','LOCATIONAL_CLEARANCE',NULL,1,0,'[:]',NULL,NULL,'ZONECLASS',NULL);


insert into obo_variable 
select * 
from ztmp_obo_variable z 
where objid not in ( 
	select objid from obo_variable where objid = z.objid 
)
go 

insert into obo_variable 
select 
	[objid], [state], [name], [caption], [description], [datatype], [doctypeid], [category], 
	[sortorder], [system], [arrayvalues], [unit], [occupancytypeid], [lookuplistname], 0 as [multiselect]	
from obo_puerto.dbo.obo_variable v 
where objid not in ( 
	select objid from obo_variable where objid = v.objid 
)
go 

drop table ztmp_obo_variable
go 


update aa set 
	aa.endorserid = bb.endorserid, 
	aa.approverid = bb.approverid 
from 
	obo_doctype aa, 
	(
		select objid, 
			(select endorserid from obo_puerto.dbo.obo_doctype where objid = d.objid) as endorserid, 
			(select approverid from obo_puerto.dbo.obo_doctype where objid = d.objid) as approverid 
		from obo_doctype d 
	)bb 
where aa.objid = bb.objid 
go 


update aa set 
	aa.endorserid = bb.newendorserid 
from 
	obo_doctype aa, 
	( 
		select distinct 
			d.endorserid, s.objid as newendorserid
		from obo_doctype d 
			left join sys_signature s on s.objid = d.endorserid 
		where d.endorserid is not null 
	)bb 
where aa.endorserid = bb.endorserid
go 

update aa set 
	aa.approverid = bb.newapproverid 
from 
	obo_doctype aa, 
	( 
		select distinct 
			d.approverid, s.objid as newapproverid
		from obo_doctype d 
			left join sys_signature s on s.objid = d.approverid 
		where d.approverid is not null 
	)bb 
where aa.approverid = bb.approverid
go 


INSERT INTO obo_professional_info 
SELECT * FROM obo_puerto.dbo.obo_professional_info p 
where p.objid not in (
	select objid from obo_professional_info  where objid = p.objid 
)
go 
INSERT INTO obo_professional 
SELECT * FROM obo_puerto.dbo.obo_professional p 
where p.objid not in (
	select objid from obo_professional  where objid = p.objid 
) 
go 


-- start migration process
INSERT INTO obo_app 
(objid,doctypeid,appno,appdate,trackingno,contact_name,contact_detail,contact_email,contact_mobileno,txnmode,
	orgcode,createdby_objid,createdby_name,dtcreated)
SELECT 
objid,'BUILDING_PERMIT',appno,appdate,trackingno,contact_name,contact_detail,contact_email,contact_mobileno,txnmode,
orgcode,createdby_objid,createdby_name,dtcreated
FROM obo_puerto.dbo.building_permit p 
where objid not in (
	select objid from obo_app where objid = p.objid 
)
go 

INSERT INTO building_permit 
(objid,apptype,txntype,amount,description,title,occupancytypeid,numunits,fixedcost,projectcost,dtproposedconstruction,
dtexpectedcompletion,totalfloorarea,height,numfloors,worktypes,location_lotno,location_blockno,location_street,location_barangay_name,
location_barangay_objid,supervisorid,location_unitno,location_bldgno,location_bldgname,location_subdivision,location_lotarea)
SELECT 
objid,apptype,txntype,amount,description,title,occupancytypeid,numunits,fixedcost,projectcost,dtproposedconstruction,
dtexpectedcompletion,totalfloorarea,height,numfloors,worktypes,location_lotno,location_blockno,location_street,location_barangay_name,
location_barangay_objid,supervisorid,location_unitno,location_bldgno,location_bldgname,location_subdivision,location_lotarea
FROM obo_puerto.dbo.building_permit p 
where objid not in (
	select objid from building_permit where objid = p.objid 
)
go 

INSERT INTO building_permit_task
(taskid,refid,parentprocessid,state,startdate,enddate,assignee_objid,assignee_name,actor_objid,actor_name,message,dtcreated,prevtaskid)
SELECT 
taskid,refid,parentprocessid,state,startdate,enddate,assignee_objid,assignee_name,actor_objid,actor_name,message,dtcreated,prevtaskid
FROM obo_puerto.dbo.building_permit_task t 
where taskid not in (
	select taskid from building_permit_task where taskid = t.taskid 
) 
go 


INSERT INTO obo_app_entity
(
objid,appid,profileid,entitytype,profileno,name,firstname,middlename,lastname,resident,address_objid,address_text,address_unitno,address_bldgno,
address_bldgname,address_street,address_subdivision,address_barangay_objid,address_barangay_name,address_citymunicipality,address_province,
tin,email,mobileno,phoneno,id_type_name,id_idno,id_placeissued,id_dtissued
)
SELECT 
objid,appid,profileid,entitytype,profileno,name,firstname,middlename,lastname,resident,address_objid,address_text,address_unitno,address_bldgno,
address_bldgname,address_street,address_subdivision,address_barangay_objid,address_barangay_name,address_citymunicipality,address_province,
tin,email,mobileno,phoneno,id_type_name,id_idno,id_placeissued,id_dtissued
FROM obo_puerto.dbo.building_permit_entity e 
where objid not in (
	select objid from obo_app_entity where objid = e.objid 
)
go 

-- update applicantid and taskid
UPDATE a set 
	a.applicantid = b.applicantid 
from obo_app a, obo_puerto.dbo.building_permit b 
WHERE a.objid = b.objid
go 

UPDATE b1 set 
	b1.taskid = b2.taskid 
from building_permit b1, obo_puerto.dbo.building_permit b2 
WHERE b1.objid = b2.objid
go 

-- insert building_permit_rpu
INSERT INTO building_permit_rpu
( 
objid,appid,tdno,tctno,pin,barangay,titleno,lotno,blockno,areasqm,classcode,ownerid,street,refid,bill_amtdue,
lotowned,taxclearanceid,truecopycertid,taxclearancefee,truecopycertfee
)
SELECT 
objid,appid,tdno,tctno,pin,barangay,titleno,lotno,blockno,areasqm,classcode,ownerid,street,refid,bill_amtdue,
lotowned,taxclearanceid,truecopycertid,0,0
FROM obo_puerto.dbo.building_permit_rpu r 
where objid not in (
	select objid from building_permit_rpu where objid = r.objid 
)
go 

INSERT INTO [dbo].[obo_doctype] ([objid], [title], [sectionid], [sortorder], [type], [template], [autocreate], [issuetype], [requirefee], [appnopattern], [controlnopattern], [subtypeof], [apptype], [system], [role], [endorserid], [approverid], [reportheader], [refdoc], [includeinemail]) 
VALUES ('BFP_FIRE_SAFETY_CLEARANCE', 'BFP ELECTRICAL CLEARANCE', 'BFP', NULL, 'CLEARANCE', 'reports/bfp/fsce', '0', '3', '1', NULL, 'FSCECNO.R4B-[YYYYmm]-[%05d]', NULL, 'building', NULL, 'BFP_RELEASER', '8f07087:1765ef572b8:-7ffc', 'USR4ac8bf36:17645fd926a:-7c04', NULL, NULL, '1');


-- insert docs. we'll have to insert ignore first since there are documents that cannot be added because they are in conflict
select objid, appid, state, doctypeid, worktypes, remarks, amount, projectcost, equipmentcost
into ztmp_obo_app_doc
from obo_puerto.dbo.building_permit_doc d 
where objid not in (
	select objid from obo_app_doc where objid = d.objid 
)
order by appid,doctypeid
go 

INSERT INTO obo_app_doc (
	objid, appid, state, doctypeid, worktypes, remarks, amount, projectcost, equipmentcost
)
select 
	z.objid, z.appid, z.state, z.doctypeid, z.worktypes, z.remarks, z.amount, z.projectcost, z.equipmentcost
from ( 
	select appid,doctypeid,count(*) as icount 
	from ztmp_obo_app_doc
	group by appid,doctypeid 
	having count(*) = 1
)tmp1, ztmp_obo_app_doc z
where z.appid = tmp1.appid 
	and z.doctypeid = tmp1.doctypeid 
go 

insert into obo_app_doc (
	objid, appid, state, doctypeid, worktypes, remarks, amount, projectcost, equipmentcost
)
select 
	z.objid, z.appid, z.state, z.doctypeid, z.worktypes, z.remarks, z.amount, z.projectcost, z.equipmentcost
from ( 
	select z.objid, 
		(select count(*) from obo_puerto.dbo.building_permit_info where appid = z.appid and parentid = z.objid) as infocount, 
		(select count(*) from obo_puerto.dbo.building_permit_fee where appid = z.appid and parentid = z.objid) as feecount 
	from ( 
		select appid,doctypeid,count(*) as icount 
		from ztmp_obo_app_doc
		group by appid,doctypeid 
		having count(*) > 1 
	)tmp1, ztmp_obo_app_doc z 
	where z.appid = tmp1.appid 
		and z.doctypeid = tmp1.doctypeid 
)tmp2, ztmp_obo_app_doc z 
where z.objid = tmp2.objid 
	and (tmp2.infocount + tmp2.feecount) > 0 
go 

drop table ztmp_obo_app_doc
go 


INSERT INTO obo_app_doc_info 
(objid,appid,parentid,name,stringvalue,decimalvalue,intvalue,datevalue,booleanvalue,remarks)
SELECT 
objid,appid,parentid,name,stringvalue,decimalvalue,intvalue,datevalue,booleanvalue,remarks
FROM obo_puerto.dbo.building_permit_info p 
where objid not in (
	select objid from obo_app_doc_info where objid = p.objid 
)
go 


INSERT INTO obo_app_doc_info 
(objid,appid,parentid,name,stringvalue,decimalvalue,intvalue,datevalue,booleanvalue,remarks)
SELECT 
objid,appid,parentid,name,stringvalue,decimalvalue,intvalue,datevalue,booleanvalue,remarks
FROM obo_puerto.dbo.building_permit_info p 
where objid not in (
	select objid from obo_app_doc_info where objid = p.objid 
)
go 


INSERT INTO obo_app_fee 
(objid,appid,parentid,itemid,amount,amtpaid,remarks)
SELECT 
objid,appid,parentid,itemid,amount,amtpaid,remarks
FROM obo_puerto.dbo.building_permit_fee p 
where objid not in (
	select objid from obo_app_fee  where objid = p.objid 
)
go 


INSERT INTO obo_payment 
( objid,appid,refno,refdate,refid,reftype,amount,voided )
SELECT  
objid,appid,refno,refdate,refid,reftype,amount,voided
FROM obo_puerto.dbo.building_permit_payment p 
where objid not in (
	select objid from obo_payment  where objid = p.objid 
)
go 


INSERT INTO obo_control
(objid,state,appid,
doctypeid,controlno,dtissued,issuedby_objid,issuedby_name,expirydate,
remarks,template,endorserid,approverid,reportheader)
SELECT 
objid,state,appid,
doctypeid,controlno,dtissued,issuedby_objid,issuedby_name,expirydate,
remarks,template,endorserid,approverid,reportheader
FROM obo_puerto.dbo.obo_control c 
where objid not in (
	select objid from obo_control where objid = c.objid 
)
go 



-- insert building permit document
INSERT INTO obo_app_doc 
(objid,appid,state,doctypeid,amount,controlid) 
select * 
from ( 
	SELECT 
	CONCAT(objid,':BUILDING_PERMIT') AS objid, objid AS appid, 0 AS state, 'BUILDING_PERMIT' AS doctypeid, 0 AS amount,controlid
	FROM obo_puerto.dbo.building_permit 
)tmp1 
where (
	select count(*) from obo_app_doc 
	where appid = tmp1.appid and doctypeid = tmp1.doctypeid 
) = 0 
go 


INSERT INTO obo_app_doc 
(objid,appid,state,doctypeid,amount)
select * 
from ( 
	SELECT 
	CONCAT(objid,':BUILDING_RPT') AS objid,objid AS appid,0 AS state, 'BUILDING_RPT' AS doctypeid, 0 AS amount
	FROM obo_puerto.dbo.building_permit
)tmp1 
where (
	select count(*) from obo_app_doc 
	where appid = tmp1.appid and doctypeid = tmp1.doctypeid 
) = 0 
go 


-- update the controlid of the obo_app_doc
UPDATE d1 set 
	d1.controlid = bd.controlid 
from obo_app_doc d1, obo_puerto.dbo.building_permit_doc bd 
WHERE d1.objid = bd.objid
go 


-- correct the obo_control by updating the appid and doctypeid
UPDATE oc set 
	oc.appid = doc.appid, oc.docid=doc.objid 
from obo_control oc, obo_app_doc doc 
WHERE doc.controlid=oc.objid
go 

-- fix the current task states
UPDATE  building_permit_task 
SET state = 'trade-verification' 
WHERE state='verification'
go 


INSERT INTO obo_app_requirement 
(objid,appid,parentid,typeid,state,remarks,reviewer_objid,reviewer_name,dtreviewed)
SELECT
objid,appid,parentid,typeid,state,remarks,reviewer_objid,reviewer_name,dtreviewed
FROM obo_puerto.dbo.building_permit_requirement r 
where objid not in (
	select objid from obo_app_requirement where objid = r.objid 
)
go 

UPDATE r1 set 
	r1.supersederid = r2.supersederid 
from obo_app_requirement r1, obo_puerto.dbo.building_permit_requirement r2 
WHERE r1.objid = r2.objid
go 


-- drop index uix_building_permit_transmittal_taskid on obo_app_transmittal
-- go 
-- create index ix_taskid on obo_app_transmittal (taskid) 
-- go 

INSERT INTO obo_app_transmittal 
( objid,appid,state,type,taskid,dtcreated,createdby_objid,createdby_name,approverid,endorserid,template,reportheader )
SELECT 
objid,appid,state,type,taskid,dtcreated,createdby_objid,createdby_name,approverid,endorserid,template,reportheader
FROM obo_puerto.dbo.building_permit_transmittal t 
WHERE type = 'requirement' 
	and objid not in (
		select objid from obo_app_transmittal where objid = t.objid 
	)
go 


UPDATE r1 set 
	r1.transmittalid = r2.transmittalid 
from obo_app_requirement r1, obo_puerto.dbo.building_permit_requirement r2 
WHERE r1.objid = r2.objid
go 


INSERT INTO obo_app_doc_checklist
(objid,	parentid,	typeid,	[values])	
SELECT 
objid,	
parentid,	
typeid,	
[values]
FROM obo_puerto.dbo.building_permit_checklist c 
where objid not in (
	select objid from obo_app_doc_checklist where objid = c.objid 
)
go 




-- migrate the building evaluation,task and findings
INSERT INTO obo_app_taskitem 
(objid,appid,typeid)
select * 
from ( 
	SELECT 
		objid,appid,CONCAT('BUILDING:',typeid) AS typeid
	FROM obo_puerto.dbo.building_evaluation 
)tmp1 
where (
	select count(*) from obo_app_taskitem 
	where appid = tmp1.appid and typeid = tmp1.typeid 
) = 0 
go 


INSERT INTO obo_app_taskitem_task 
(taskid,refid,parentprocessid,state,startdate,enddate,assignee_objid,assignee_name,actor_objid,actor_name,message,dtcreated,prevtaskid)
SELECT 
taskid,refid,parentprocessid,state,startdate,enddate,assignee_objid,assignee_name,actor_objid,actor_name,message,dtcreated,prevtaskid
FROM obo_puerto.dbo.building_evaluation_task t 
where taskid not in (
	select taskid from obo_app_taskitem_task where taskid = t.taskid 
)
go

UPDATE t1 set 
	t1.taskid = t2.taskid 
from obo_app_taskitem t1, obo_puerto.dbo.building_evaluation t2 
WHERE t1.objid = t2.objid
go 

-- findings 
INSERT INTO obo_app_taskitem_finding
(objid,appid,parentid,rootid,particulars,dtcreated,createdby_objid,createdby_name,state)
SELECT
objid,appid,parentid,rootid,particulars,dtcreated,createdby_objid,createdby_name,state
FROM obo_puerto.dbo.building_evaluation_finding f 
where objid not in (
	select objid from obo_app_taskitem_finding where objid = f.objid 
)
go 


INSERT INTO obo_app_transmittal 
( objid,appid,state,type,taskid,dtcreated,createdby_objid,createdby_name,approverid,endorserid,template,reportheader )
SELECT 
objid,appid,state,type,taskid,dtcreated,createdby_objid,createdby_name,approverid,endorserid,template,reportheader
FROM obo_puerto.dbo.building_permit_transmittal t 
WHERE type <> 'requirement' 
	and objid not in (
		select objid from obo_app_transmittal  where objid = t.objid 
	) 
go 


UPDATE r1 set 
 	r1.transmittalid = r2.transmittalid, r1.supersederid = r2.supersederid  
from obo_app_taskitem_finding r1, obo_puerto.dbo.building_evaluation_finding r2 
WHERE r1.objid = r2.objid
go 


-- correct entries
-- fix the current task states
UPDATE  building_permit_task 
SET state = 'trade-verification' WHERE state='verification'
go


UPDATE obo_app_taskitem_task 
SET state = 'end' WHERE state IN ('obo-processing', 'releasing' )
go 

-- ADD PROFESSIONALS
INSERT INTO obo_app_professional
( objid, appid, sectionid, designprofessionalid, supervisorid, doctypeid )
select * 
from ( 
	SELECT 
		CONCAT(a.appid,':',doctypeid) AS objid, a.appid, NULL AS sectionid, 
		MAX(a.designprofessionalid) AS designprofessionalid, MAX(a.supervisorid) AS supervisorid, a.doctypeid  
	FROM (
		SELECT appid, doctypeid, designprofessionalid, NULL AS supervisorid 
		FROM obo_puerto.dbo.building_permit_doc 
		WHERE NOT( designprofessionalid IS NULL ) 
		UNION 
		SELECT appid, doctypeid, NULL AS designprofessionalid, supervisorid 
		FROM  obo_puerto.dbo.building_permit_doc 
		WHERE NOT( supervisorid IS NULL )
	) a 
	GROUP BY a.appid, a.doctypeid 
)tmp1 
where objid not in (
	select objid from obo_app_professional where objid = tmp1.objid 
) 
go 


-- FIND THE sectionid per professional
UPDATE ap set 
	ap.sectionid = dt.sectionid 
from obo_app_professional ap, obo_doctype dt 
WHERE ap.doctypeid = dt.objid 
go 


-- update views
if object_id('dbo.vw_building_permit', 'V') IS NOT NULL 
   drop view dbo.vw_building_permit; 
go
CREATE VIEW vw_building_permit AS select 
a.objid AS objid,
a.doctypeid AS doctypeid,
a.appno AS appno,
a.appdate AS appdate,
a.trackingno AS trackingno,
a.applicantid AS applicantid,
a.contact_name AS contact_name,
a.contact_detail AS contact_detail,
a.contact_email AS contact_email,
a.contact_mobileno AS contact_mobileno,
a.contact_phoneno AS contact_phoneno,
a.txnmode AS txnmode,
a.orgcode AS orgcode,
a.createdby_objid AS createdby_objid,
a.createdby_name AS createdby_name,
a.dtcreated AS dtcreated,
bp.apptype AS apptype,
bp.taskid AS taskid,
bp.txntype AS txntype,
bp.amount AS amount,
bp.description AS description,
bp.title AS title,
bp.occupancytypeid AS occupancytypeid,
bp.numunits AS numunits,
bp.fixedcost AS fixedcost,
bp.projectcost AS projectcost,
bp.dtproposedconstruction AS dtproposedconstruction,
bp.dtexpectedcompletion AS dtexpectedcompletion,
bp.totalfloorarea AS totalfloorarea,
bp.height AS height,
bp.numfloors AS numfloors,
bp.worktypes AS worktypes,
bp.location_lotno AS location_lotno,
bp.location_blockno AS location_blockno,
bp.location_street AS location_street,
bp.location_barangay_name AS location_barangay_name,
bp.location_barangay_objid AS location_barangay_objid,
bp.supervisorid AS supervisorid,
bp.location_unitno AS location_unitno,
bp.location_bldgno AS location_bldgno,
bp.location_bldgname AS location_bldgname,
bp.location_subdivision AS location_subdivision,
bp.location_lotarea AS location_lotarea,
ae.name AS applicant_name,
bt.objid AS occupancytype_objid,
bt.title AS occupancytype_title,
od.objid AS occupancytype_division_objid,
od.title AS occupancytype_division_title,
og.objid AS occupancytype_group_objid,
og.title AS occupancytype_group_title,
ltrim(concat(
	(case when bp.location_unitno is null then '' else concat(' ',bp.location_unitno) end),
	(case when bp.location_bldgno is null then '' else concat(' ',bp.location_bldgno) end),
	(case when bp.location_bldgname is null then '' else concat(' ',bp.location_bldgname) end),
	(case when bp.location_lotno is null then '' else concat(' Lot.',bp.location_lotno) end),
	(case when bp.location_blockno is null then '' else concat(' Blk.',bp.location_blockno) end),
	(case when bp.location_street is null then '' else concat(' ',bp.location_street) end),
	(case when bp.location_subdivision is null then '' else concat(', ',bp.location_subdivision) end),
	(case when bp.location_barangay_name is null then '' else concat(', ',bp.location_barangay_name) end)
)) AS location_text,
t.state AS task_state,
t.dtcreated AS task_dtcreated,
t.startdate AS task_startdate,
t.enddate AS task_enddate,
t.assignee_objid AS task_assignee_objid,
t.assignee_name AS task_assignee_name,
t.actor_objid AS task_actor_objid,
t.actor_name AS task_actor_name,
sn.title AS task_title,
sn.tracktime AS task_tracktime,
pmt.objid AS controlid,
pmt.controlno AS controlno,
pmt.expirydate AS expirydate,
pmt.dtissued AS dtissued,
pmt.issuedby_name AS issuedby_name,
pmt.approverid AS approverid,
pmt.endorserid AS endorserid,
pmt.template AS template,
pmt.reportheader AS reportheader 
from obo_app a 
	inner join building_permit bp on a.objid = bp.objid
	inner join building_permit_task t on bp.taskid = t.taskid 
	inner join obo_app_entity ae on a.applicantid = ae.objid
	inner join sys_wf_node sn on (sn.processname = 'building_permit' and sn.name = t.state) 
	inner join obo_occupancy_type bt on bp.occupancytypeid = bt.objid 
	inner join obo_occupancy_type_division od on bt.divisionid = od.objid 
	inner join obo_occupancy_type_group og on od.groupid = og.objid
	left join obo_control pmt on (pmt.appid = a.objid and pmt.doctypeid = 'BUILDING_PERMIT')
go 



if object_id('dbo.vw_obo_app', 'V') IS NOT NULL 
   drop view dbo.vw_obo_app; 
go
CREATE VIEW vw_obo_app AS select 
app.objid AS objid,
app.doctypeid AS doctypeid,
app.appno AS appno,
app.appdate AS appdate,
app.trackingno AS trackingno,
app.applicantid AS applicantid,
app.contact_name AS contact_name,
app.contact_detail AS contact_detail,
app.contact_email AS contact_email,
app.contact_mobileno AS contact_mobileno,
app.contact_phoneno AS contact_phoneno,
app.txnmode AS txnmode,
app.orgcode AS orgcode,
app.createdby_objid AS createdby_objid,
app.createdby_name AS createdby_name,
app.dtcreated AS dtcreated,
'building_permit' AS appclass,bp.title AS title,
ltrim(concat(
   (case when bp.location_unitno is null then '' else concat(' ',bp.location_unitno) end),
   (case when bp.location_bldgno is null then '' else concat(' ',bp.location_bldgno) end),
   (case when bp.location_bldgname is null then '' else concat(' ',bp.location_bldgname) end),
   (case when bp.location_lotno is null then '' else concat(' Lot.',bp.location_lotno) end),
   (case when bp.location_blockno is null then '' else concat(' Blk.',bp.location_blockno) end),
   (case when bp.location_street is null then '' else concat(' ',bp.location_street) end),
   (case when bp.location_subdivision is null then '' else concat(', ',bp.location_subdivision) end),
   (case when bp.location_barangay_name is null then '' else concat(', ',bp.location_barangay_name) end)
)) AS location_text,
be.name AS applicant_name,
be.address_text AS applicant_address_text,
be.profileid AS applicant_profileid,
bt.state AS task_state,
bt.assignee_objid AS task_assignee_objid,
'building_permit' AS processname,
'BUILDING PERMIT' AS doctitle,
'vw_building_permit' AS schemaname 
from obo_app app 
   inner join building_permit bp on app.objid = bp.objid 
   inner join obo_app_entity be on app.applicantid = be.objid 
   inner join building_permit_task bt on bp.taskid = bt.taskid 
union 
select 
app.objid AS objid,
app.doctypeid AS doctypeid,
app.appno AS appno,
app.appdate AS appdate,
app.trackingno AS trackingno,
app.applicantid AS applicantid,
app.contact_name AS contact_name,
app.contact_detail AS contact_detail,
app.contact_email AS contact_email,
app.contact_mobileno AS contact_mobileno,
app.contact_phoneno AS contact_phoneno,
app.txnmode AS txnmode,
app.orgcode AS orgcode,
app.createdby_objid AS createdby_objid,
app.createdby_name AS createdby_name,
app.dtcreated AS dtcreated,
'occupancy_certificate' AS appclass,bp.title AS title,
ltrim(concat(
   (case when bp.location_unitno is null then '' else concat(' ',bp.location_unitno) end),
   (case when bp.location_bldgno is null then '' else concat(' ',bp.location_bldgno) end),
   (case when bp.location_bldgname is null then '' else concat(' ',bp.location_bldgname) end),
   (case when bp.location_lotno is null then '' else concat(' Lot.',bp.location_lotno) end),
   (case when bp.location_blockno is null then '' else concat(' Blk.',bp.location_blockno) end),
   (case when bp.location_street is null then '' else concat(' ',bp.location_street) end),
   (case when bp.location_subdivision is null then '' else concat(', ',bp.location_subdivision) end),
   (case when bp.location_barangay_name is null then '' else concat(', ',bp.location_barangay_name) end)
)) AS location_text,
be.name AS applicant_name,
be.address_text AS applicant_address_text,
be.profileid AS applicant_profileid,
bt.state AS task_state,
bt.assignee_objid AS task_assignee_objid,
'occupancy_certificate' AS processname,
'OCCUPANCY CERTIFICATE' AS doctitle,
'vw_occupancy_certificate' AS schemaname 
from obo_app app 
   inner join occupancy_certificate oc on oc.objid = app.objid
   inner join building_permit bp on oc.bldgpermitid = bp.objid
   inner join obo_app_entity be on app.applicantid = be.objid
   inner join occupancy_certificate_task bt on oc.taskid = bt.taskid
go 



if object_id('dbo.vw_obo_app_doc', 'V') IS NOT NULL 
   drop view dbo.vw_obo_app_doc; 
go
CREATE VIEW vw_obo_app_doc AS select 
a.objid AS objid,
a.appid AS appid,
a.state AS state,
a.doctypeid AS doctypeid,
a.worktypes AS worktypes,
a.remarks AS remarks,
a.amount AS amount,
a.controlid AS controlid,
a.projectcost AS projectcost,
a.equipmentcost AS equipmentcost,
os.org_objid AS org_objid,
ba.task_state AS task_state,
ba.task_assignee_objid AS task_assignee_objid,
iss.controlno AS controlno,
iss.dtissued AS dtissued,
iss.expirydate AS expirydate,
iss.issuedby_name AS issuedby_name,
iss.issuedby_objid AS issuedby_objid,
iss.template AS template,
iss.endorserid AS endorserid,
iss.approverid AS approverid,
od.sectionid AS sectionid 
from obo_app_doc a 
	inner join vw_obo_app ba on a.appid = ba.objid
	inner join obo_doctype od on a.doctypeid = od.objid
	left join obo_section os on od.sectionid = os.objid
	left join obo_control iss on a.controlid = iss.objid
go 



if object_id('dbo.vw_obo_app_doc_info', 'V') IS NOT NULL 
   drop view dbo.vw_obo_app_doc_info; 
go
CREATE VIEW vw_obo_app_doc_info AS select 
ai.objid AS objid,
ai.appid AS appid,
ai.parentid AS parentid,
ai.name AS name,
ai.stringvalue AS stringvalue,
ai.decimalvalue AS decimalvalue,
ai.intvalue AS intvalue,
ai.datevalue AS datevalue,
ai.booleanvalue AS booleanvalue,
ai.remarks AS remarks,
ai.lookupkey AS lookupkey,
ai.lookupvalue AS lookupvalue,
ov.datatype AS datatype,
ov.doctypeid AS doctypeid,
ov.unit AS unit,
ov.caption AS caption,
ov.category AS category,
ov.sortorder AS sortorder,
ov.lookuplistname AS lookuplistname,
ov.arrayvalues AS arrayvalues,
ov.multiselect AS multiselect 
from obo_app_doc_info ai 
	inner join obo_variable ov on ov.objid = ai.name
go 




if object_id('dbo.vw_obo_app_taskitem', 'V') IS NOT NULL 
   drop view dbo.vw_obo_app_taskitem; 
go
CREATE VIEW vw_obo_app_taskitem AS select 
a.objid AS objid,
a.appid AS appid,
a.typeid AS typeid,
a.taskid AS taskid,
os.objid AS sectionid,
os.org_objid AS org_objid,
et.title AS type_title,
et.sortindex AS type_sortindex,
et.joinstate AS type_joinstate,
app.task_state AS app_task_state,
t.state AS task_state,
t.dtcreated AS task_dtcreated,
t.startdate AS task_startdate,
t.enddate AS task_enddate,
t.assignee_objid AS task_assignee_objid,
t.assignee_name AS task_assignee_name,
t.actor_objid AS task_actor_objid,
t.actor_name AS task_actor_name,
sn.title AS task_title,
sn.tracktime AS task_tracktime 
from obo_app_taskitem a 
	inner join obo_app_taskitem_task t on a.taskid = t.taskid
	inner join obo_taskitem_type et on a.typeid = et.objid
	inner join sys_wf_node sn on (sn.processname = 'obo_app_taskitem' and sn.name = t.state) 
	inner join vw_obo_app app on a.appid = app.objid
	left join obo_section os on et.sectionid = os.objid
go 



if object_id('dbo.vw_obo_doctype', 'V') IS NOT NULL 
   drop view dbo.vw_obo_doctype; 
go
CREATE VIEW vw_obo_doctype AS select 
od.objid AS objid,
od.title AS title,
od.sectionid AS sectionid,
od.sortorder AS sortorder,
od.type AS type,
od.template AS template,
od.autocreate AS autocreate,
od.issuetype AS issuetype,
od.requirefee AS requirefee,
od.appnopattern AS appnopattern,
od.controlnopattern AS controlnopattern,
od.subtypeof AS subtypeof,
od.apptype AS apptype,
od.system AS system,
od.role AS role,
od.endorserid AS endorserid,
od.approverid AS approverid,
od.reportheader AS reportheader,
od.refdoc AS refdoc,
od.includeinemail AS includeinemail,
os.org_objid AS org_objid,
os.org_name AS org_name 
from obo_doctype od 
	left join obo_section os on od.sectionid = os.objid
go 



if object_id('dbo.vw_obo_occupancy_type', 'V') IS NOT NULL 
   drop view dbo.vw_obo_occupancy_type; 
go
CREATE VIEW vw_obo_occupancy_type AS select 
ot.objid AS objid,
ot.divisionid AS divisionid,
ot.title AS title,
od.objid AS division_objid,
od.title AS division_title,
og.objid AS group_objid,
og.title AS group_title 
from obo_occupancy_type ot 
	inner join obo_occupancy_type_division od on ot.divisionid = od.objid 
	inner join obo_occupancy_type_group og on od.groupid = og.objid 
go 




if object_id('dbo.vw_obo_payment', 'V') IS NOT NULL 
   drop view dbo.vw_obo_payment; 
go
CREATE VIEW vw_obo_payment AS select 
bf.objid AS objid,
bf.appid AS appid,
bf.parentid AS parentid,
bf.itemid AS itemid,
bf.amount AS amount,
bf.amtpaid AS amtpaid,
bf.remarks AS remarks,
oi.objid AS item_objid,
oi.title AS item_title,
oi.sortorder AS item_sortorder,
pt.reftype AS payment_type,
pt.refno AS payment_refno,
pt.refid AS payment_refid,
pt.refdate AS payment_refdate 
from obo_app_fee bf 
	inner join obo_itemaccount oi on bf.itemid = oi.objid
	left join obo_payment pt on bf.appid = pt.appid
where (pt.voided is null or pt.voided = 0)
go 



if object_id('dbo.vw_obo_professional', 'V') IS NOT NULL 
   drop view dbo.vw_obo_professional; 
go
CREATE VIEW vw_obo_professional AS select 
pi.objid AS objid, 
pi.firstname AS firstname, 
pi.middlename AS middlename, 
pi.lastname AS lastname, 
pi.resident AS resident, 
pi.address_objid AS address_objid, 
pi.address_text AS address_text, 
pi.address_unitno AS address_unitno, 
pi.address_bldgno AS address_bldgno, 
pi.address_bldgname AS address_bldgname, 
pi.address_street AS address_street, 
pi.address_subdivision AS address_subdivision, 
pi.address_barangay_objid AS address_barangay_objid, 
pi.address_barangay_name AS address_barangay_name, 
pi.address_citymunicipality AS address_citymunicipality, 
pi.address_province AS address_province, 
pi.tin AS tin, 
pi.email AS email, 
pi.mobileno AS mobileno, 
pi.phoneno AS phoneno, 
pi.id_idno AS id_idno, 
pi.id_type_name AS id_type_name, 
pi.id_dtissued AS id_dtissued, 
pi.id_placeissued AS id_placeissued, 
pi.profession AS profession, 
pi.prc_idno AS prc_idno, 
pi.prc_dtissued AS prc_dtissued, 
pi.prc_dtvalid AS prc_dtvalid, 
pi.prc_placeissued AS prc_placeissued, 
pi.ptr_refno AS ptr_refno, 
pi.ptr_dtissued AS ptr_dtissued, 
pi.ptr_placeissued AS ptr_placeissued, 
pi.profid AS profid, 
pi.system AS system, 
concat(pi.lastname,', ',pi.firstname,' ',substring(pi.middlename,0,1),'.') AS name,
id.caption AS id_type_caption, 
id.title AS id_type_title  
from obo_professional p 
	inner join obo_professional_info pi on p.infoid = pi.objid  
	left join idtype id on pi.id_type_name = id.name 
go 



if object_id('dbo.vw_obo_professional_info', 'V') IS NOT NULL 
   drop view dbo.vw_obo_professional_info; 
go
CREATE VIEW vw_obo_professional_info AS select 
pi.objid AS objid,
pi.firstname AS firstname,
pi.middlename AS middlename,
pi.lastname AS lastname,
pi.resident AS resident,
pi.address_objid AS address_objid,
pi.address_text AS address_text,
pi.address_unitno AS address_unitno,
pi.address_bldgno AS address_bldgno,
pi.address_bldgname AS address_bldgname,
pi.address_street AS address_street,
pi.address_subdivision AS address_subdivision,
pi.address_barangay_objid AS address_barangay_objid,
pi.address_barangay_name AS address_barangay_name,
pi.address_citymunicipality AS address_citymunicipality,
pi.address_province AS address_province,
pi.tin AS tin,
pi.email AS email,
pi.mobileno AS mobileno,
pi.phoneno AS phoneno,
pi.id_idno AS id_idno,
pi.id_type_name AS id_type_name,
pi.id_dtissued AS id_dtissued,
pi.id_placeissued AS id_placeissued,
pi.profession AS profession,
pi.prc_idno AS prc_idno,
pi.prc_dtissued AS prc_dtissued,
pi.prc_dtvalid AS prc_dtvalid,
pi.prc_placeissued AS prc_placeissued,
pi.ptr_refno AS ptr_refno,
pi.ptr_dtissued AS ptr_dtissued,
pi.ptr_placeissued AS ptr_placeissued,
pi.profid AS profid,
pi.system AS system,
concat(pi.lastname,', ',pi.firstname,' ',substring(pi.middlename,0,1),'.') AS name,
id.caption AS id_type_caption,
id.title AS id_type_title
 from obo_professional_info pi 
 	left join idtype id on pi.id_type_name = id.name
 go 



if object_id('dbo.vw_obo_professional_info_lookup', 'V') IS NOT NULL 
   drop view dbo.vw_obo_professional_info_lookup; 
go
CREATE VIEW vw_obo_professional_info_lookup AS select 
pi.objid AS objid, 
pi.firstname AS firstname, 
pi.middlename AS middlename, 
pi.lastname AS lastname, 
pi.resident AS resident, 
pi.address_objid AS address_objid, 
pi.address_text AS address_text, 
pi.address_unitno AS address_unitno, 
pi.address_bldgno AS address_bldgno, 
pi.address_bldgname AS address_bldgname, 
pi.address_street AS address_street, 
pi.address_subdivision AS address_subdivision, 
pi.address_barangay_objid AS address_barangay_objid, 
pi.address_barangay_name AS address_barangay_name, 
pi.address_citymunicipality AS address_citymunicipality, 
pi.address_province AS address_province, 
pi.tin AS tin, 
pi.email AS email, 
pi.mobileno AS mobileno, 
pi.phoneno AS phoneno, 
pi.id_idno AS id_idno, 
pi.id_type_name AS id_type_name, 
pi.id_dtissued AS id_dtissued, 
pi.id_placeissued AS id_placeissued, 
pi.profession AS profession, 
pi.prc_idno AS prc_idno, 
pi.prc_dtissued AS prc_dtissued, 
pi.prc_dtvalid AS prc_dtvalid, 
pi.prc_placeissued AS prc_placeissued, 
pi.ptr_refno AS ptr_refno, 
pi.ptr_dtissued AS ptr_dtissued, 
pi.ptr_placeissued AS ptr_placeissued, 
pi.profid AS profid, 
pi.system AS system, 
concat(pi.lastname,', ',pi.firstname,' ',substring(pi.middlename,0,1),'.') AS name,
id.caption AS id_type_caption, 
id.title AS id_type_title  
from obo_professional_info pi 
	inner join obo_professional p on p.infoid = pi.objid 
	left join idtype id on pi.id_type_name = id.name 
union all 
select 
pi.objid AS objid, 
pi.firstname AS firstname, 
pi.middlename AS middlename, 
pi.lastname AS lastname, 
pi.resident AS resident, 
pi.address_objid AS address_objid, 
pi.address_text AS address_text, 
pi.address_unitno AS address_unitno, 
pi.address_bldgno AS address_bldgno, 
pi.address_bldgname AS address_bldgname, 
pi.address_street AS address_street, 
pi.address_subdivision AS address_subdivision, 
pi.address_barangay_objid AS address_barangay_objid, 
pi.address_barangay_name AS address_barangay_name, 
pi.address_citymunicipality AS address_citymunicipality, 
pi.address_province AS address_province, 
pi.tin AS tin, 
pi.email AS email, 
pi.mobileno AS mobileno, 
pi.phoneno AS phoneno, 
pi.id_idno AS id_idno, 
pi.id_type_name AS id_type_name, 
pi.id_dtissued AS id_dtissued, 
pi.id_placeissued AS id_placeissued, 
pi.profession AS profession, 
pi.prc_idno AS prc_idno, 
pi.prc_dtissued AS prc_dtissued, 
pi.prc_dtvalid AS prc_dtvalid, 
pi.prc_placeissued AS prc_placeissued, 
pi.ptr_refno AS ptr_refno, 
pi.ptr_dtissued AS ptr_dtissued, 
pi.ptr_placeissued AS ptr_placeissued, 
pi.profid AS profid, 
pi.system AS system, 
concat(pi.lastname,', ',pi.firstname,' ',substring(pi.middlename,0,1),'.') AS name,
id.caption AS id_type_caption, 
id.title AS id_type_title  
from obo_professional_info pi 
	left join idtype id on pi.id_type_name = id.name 
where pi.prc_idno not in (select obo_professional.prcno from obo_professional)
go 



if object_id('dbo.vw_obo_taskitem_consolidated', 'V') IS NOT NULL 
   drop view dbo.vw_obo_taskitem_consolidated; 
go
CREATE VIEW vw_obo_taskitem_consolidated AS select 
be.objid AS objid,
be.appid AS appid,
be.typeid AS typeid,
bt.title AS type_title,
bt.sortindex AS sortindex,
betr.role AS role,
os.org_objid AS org_objid 
from obo_app_taskitem be 
	inner join obo_taskitem_type bt on be.typeid = bt.objid  
	left join obo_section os on bt.sectionid = os.objid  
	inner join obo_taskitem_type_role betr on betr.typeid = bt.objid  
union all 
select 
be.objid AS objid,
be.appid AS appid,
be.typeid AS typeid,
bt.title AS type_title,
bt.sortindex AS sortindex,
wn.role AS role,
os.org_objid AS org_objid 
from obo_app_taskitem be 
	inner join obo_taskitem_type bt on be.typeid = bt.objid  
	inner join sys_wf_node wn on (wn.processname = 'obo_app_taskitem' and wn.tracktime = 1) 
	left join obo_section os on bt.sectionid = os.objid  
where wn.name not in (
	select obo_taskitem_type_role.state from obo_taskitem_type_role 
	where obo_taskitem_type_role.typeid = be.typeid 
)
go 



if object_id('dbo.vw_occupancy_certificate', 'V') IS NOT NULL 
   drop view dbo.vw_occupancy_certificate; 
go
CREATE VIEW vw_occupancy_certificate AS select 
a.objid AS objid,
a.doctypeid AS doctypeid,
a.appno AS appno,
a.appdate AS appdate,
a.trackingno AS trackingno,
a.applicantid AS applicantid,
a.contact_name AS contact_name,
a.contact_detail AS contact_detail,
a.contact_email AS contact_email,
a.contact_mobileno AS contact_mobileno,
a.contact_phoneno AS contact_phoneno,
a.txnmode AS txnmode,
a.orgcode AS orgcode,
a.createdby_objid AS createdby_objid,
a.createdby_name AS createdby_name,
a.dtcreated AS dtcreated,
op.apptype AS apptype,
op.txntype AS txntype,
op.taskid AS taskid,
op.bldgpermitid AS bldgpermitid,
op.totalmaterialcost AS totalmaterialcost,
op.totaldirectlaborcost AS totaldirectlaborcost,
op.totalequipmentcost AS totalequipmentcost,
op.totalothercost AS totalothercost,
op.occupancytypeid AS occupancytypeid,
op.actualnumunits AS actualnumunits,
op.actualtotalfloorarea AS actualtotalfloorarea,
op.actualheight AS actualheight,
op.actualnumfloors AS actualnumfloors,
op.dtactualstarted AS dtactualstarted,
op.dtactualcompleted AS dtactualcompleted,
op.inspectiondate AS inspectiondate,
op.supervisorid AS supervisorid,
op.contractor_name AS contractor_name,
op.contractor_address AS contractor_address,
op.contractor_pcab_idno AS contractor_pcab_idno,
op.contractor_pcab_dtvalid AS contractor_pcab_dtvalid,
op.contractor_tin AS contractor_tin,
op.contractor_manager_name AS contractor_manager_name,
op.contractor_manager_email AS contractor_manager_email,
op.actualfixedcost AS actualfixedcost,
op.actualprojectcost AS actualprojectcost,
op.occupancystate AS occupancystate,
op.amount AS amount,
t.state AS task_state,
t.startdate AS task_startdate,
t.enddate AS task_enddate,
t.assignee_objid AS task_assignee_objid,
t.assignee_name AS task_assignee_name,
t.actor_objid AS task_actor_objid,
t.actor_name AS task_actor_name,
(
	select sys_wf_node.title from sys_wf_node 
	where sys_wf_node.processname = 'occupancy_certificate' 
		and sys_wf_node.name = t.state
) AS task_title, 
ot.objid AS occupancytype_objid,
ot.title AS occupancytype_title,
od.objid AS occupancytype_division_objid,
od.title AS occupancytype_division_title,
og.objid AS occupancytype_group_objid,
og.title AS occupancytype_group_title,
ctl.controlno AS controlno,
ctl.expirydate AS expirydate,
ctl.dtissued AS dtissued,
ctl.issuedby_name AS issuedby_name,
ctl.approverid AS approverid,
ctl.endorserid AS endorserid,
ctl.template AS template,
ctl.reportheader AS reportheader,
bp.title AS title,
bp.location_text AS location_text 
from obo_app a 
	inner join occupancy_certificate op on a.objid = op.objid  
	inner join vw_building_permit bp on op.bldgpermitid = bp.objid  
	inner join occupancy_certificate_task t on op.taskid = t.taskid  
	inner join obo_occupancy_type ot on op.occupancytypeid = ot.objid  
	inner join obo_occupancy_type_division od on ot.divisionid = od.objid  
	inner join obo_occupancy_type_group og on od.groupid = og.objid  
	left join obo_control ctl on (ctl.appid = a.objid and ctl.doctypeid = 'OCCUPANCY_CERTIFICATE')
go 



-- CREATE TABLE obo_appno (
--   appno varchar(50) NOT NULL,
--   appid varchar(50) NOT NULL DEFAULT '',
--   PRIMARY KEY (appid,appno) ,
--   CONSTRAINT fk_obo_appno_appid FOREIGN KEY (appid) REFERENCES obo_app (objid)
-- )
-- go 

INSERT INTO obo_appno 
SELECT appno, objid FROM
obo_app WHERE NOT(appno IS NULL)
go 



if object_id('dbo.vw_obo_app_task', 'V') IS NOT NULL 
   drop view dbo.vw_obo_app_task; 
go

CREATE VIEW vw_obo_app_task AS 
SELECT 
t.taskid,
'building_permit' AS processname,
t.refid, 
t.state, 
wf.title,
wf.tracktime,
wf.nodetype,
t.dtcreated,
t.startdate,
t.enddate, 
t.assignee_name,
t.assignee_objid 
FROM building_permit_task t
INNER JOIN sys_wf_node wf ON wf.processname = 'building_permit' AND t.state = wf.name 
AND wf.nodetype = 'state'

UNION 

SELECT 
t.taskid,
'occupancy_certificate' AS processname,
t.refid, 
t.state, 
wf.title,
wf.tracktime,
wf.nodetype,
t.dtcreated,
t.startdate,
t.enddate, 
t.assignee_name,
t.assignee_objid 
FROM occupancy_certificate_task t
INNER JOIN sys_wf_node wf ON wf.processname = 'occupancy_certificate' AND t.state = wf.name 
AND wf.nodetype = 'state'
go 


if object_id('dbo.vw_obo_app_taskitem_task', 'V') IS NOT NULL 
   drop view dbo.vw_obo_app_taskitem_task; 
go
CREATE VIEW vw_obo_app_taskitem_task AS 
SELECT 
  t.*,
	ti.appid, 
	typ.title AS section,
	typ.sectionid,
	wf.title, 
	wf.tracktime,
	typ.activationstate,
	typ.joinstate   	
FROM obo_app_taskitem_task t 
INNER JOIN obo_app_taskitem ti ON t.refid = ti.objid 
INNER JOIN obo_taskitem_type typ ON ti.typeid = typ.objid 
INNER JOIN sys_wf_node wf ON wf.processname = 'obo_app_taskitem' AND t.state = wf.name 
WHERE wf.nodetype = 'state'
go 


if object_id('dbo.vw_occupancy_certificate', 'V') IS NOT NULL 
   drop view dbo.vw_occupancy_certificate; 
go

CREATE VIEW vw_occupancy_certificate AS 
SELECT 
   a.*,
   op.apptype,
   op.txntype,
   op.taskid,
   op.bldgpermitid,
   op.totalmaterialcost,
   op.totaldirectlaborcost,
   op.totalequipmentcost,
   op.totalothercost,
   op.occupancytypeid,
   op.actualnumunits,
   op.actualtotalfloorarea,
   op.actualheight,
   op.actualnumfloors,
   op.dtactualstarted,
   op.dtactualcompleted,
   op.inspectiondate,
   op.supervisorid,
   op.contractor_name,
   op.contractor_address,
   op.contractor_pcab_idno,
   op.contractor_pcab_dtvalid,
   op.contractor_tin,
   op.contractor_manager_name,
   op.contractor_manager_email,
   op.actualfixedcost,
   op.actualprojectcost,
   op.occupancystate,
   op.amount,

   t.state AS task_state,
   t.startdate AS task_startdate,
   t.enddate AS task_enddate,
   t.assignee_objid AS task_assignee_objid,
   t.assignee_name AS task_assignee_name,
   t.actor_objid AS task_actor_objid,
   t.actor_name AS task_actor_name,
   (SELECT title FROM sys_wf_node WHERE processname = 'occupancy_certificate' AND name=t.state) AS task_title,
   ot.objid AS occupancytype_objid,
   ot.title AS occupancytype_title,   
   od.objid AS occupancytype_division_objid,
   od.title AS occupancytype_division_title,   
   og.objid AS occupancytype_group_objid,
   og.title AS occupancytype_group_title,
   ctl.controlno,
   ctl.expirydate,
   ctl.dtissued,
   ctl.issuedby_name,
   ctl.approverid,
   ctl.endorserid,
   ctl.template,
   ctl.reportheader,

   bp.title,
   bp.location_text,
   op.actualfixedcost AS fixedcost,
   op.actualprojectcost AS projectcost  

FROM obo_app a
INNER JOIN occupancy_certificate op ON  a.objid = op.objid 
INNER JOIN vw_building_permit bp ON op.bldgpermitid = bp.objid
INNER JOIN occupancy_certificate_task t ON op.taskid = t.taskid
INNER JOIN obo_occupancy_type ot ON op.occupancytypeid = ot.objid 
INNER JOIN obo_occupancy_type_division od ON ot.divisionid = od.objid 
INNER JOIN obo_occupancy_type_group og ON od.groupid = og.objid 
LEFT JOIN obo_control ctl ON ctl.appid=a.objid AND ctl.doctypeid = 'OCCUPANCY_CERTIFICATE' 
go 


update obo_app_taskitem_task set state = 'approval' where state = 'evaluation-approval'
go 

