version: "3"

services:

  mail-obo: 
    container_name: mail-obo
    image: "ramesesinc/mail-server:latest"
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./env.conf
      - ../../_custom/env.conf
    ports:
      - "2526:25"
